### ISSUE TITLE
Android Studio requires you to delete all subproject settings.gradle to work

### ISSUE THREAD

**Issue by jonalmeida** [snowplow/snowplow-android-tracker#10]
First off, this isn't really a bug we can fix, but it spoils development _immensely_. 

Because of a [bug in Android Studio](https://code.google.com/p/android/issues/detail?id=65915), there is no way to resolve subproject symbols for projects that are more that one level down. The temporary "fix" for this, is to delete the `settings.gradle` files for all subprojects in the `snowplow-android-tracker` to allow AS to recognize `android-tracker` and `java-tracker-core` as modules.

**Steps:**
- Delete `java-tracker/settings.gradle`
- Delete `java-tracker/java-tracker-core/settings.gradle`

**Things we can do:**
- If this is still an issue when we release the android tracker, we need to document this in the Setup/Troubleshooting Guide.

> **Notes:**
> We can't delete the settings.gradle the other projects since we require them to function as their own projects. This is mentioned by others in the bug report as well, so this is the only workaround atm.

_Leaving without milestone or assignee for now._

**Comment by AlexBenny** [comment]
This is quite old (2014) and not an issue now.
