### ISSUE TITLE
trackStructuredEvent value should be a Float or Double, not int

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#101]
For two reasons:

1. Scala Common Enrich can process it as a double
2. int (or float) primitive type cannot be null

**Comment by n-belokopytov** [comment]
Agreed, Google Analytics processes Long

**Comment by alexanderdean** [comment]
Thanks, scheduling

**Comment by jbeemster** [comment]
@alexanderdean with this ticket what is the preference here then; float, double or long for this value?

**Comment by alexanderdean** [comment]
Hey @jbeemster - I'd say Double, https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentManager.scala#L161
