### ISSUE TITLE
Add device sent time on outbound events

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#108]
Using new stm field

**Comment by alexanderdean** [comment]
Depends on https://github.com/snowplow/snowplow-android-tracker/issues/109

**Comment by jbeemster** [comment]
@alexanderdean do we need a properly formatted timestamp for this field or is being processed in the collector/enrich stages?

**Comment by alexanderdean** [comment]
Ah! For consistency let's match dtm, which is an epoch timestamp: https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentManager.scala#L122

**Comment by jbeemster** [comment]
Makes it easier.
