### ISSUE TITLE
Problem on SelfDescribingJson java.lang.VerifyError

### ISSUE THREAD

**Issue by gianrubio** [snowplow/snowplow-android-tracker#116]
I'm integrating snowplow-android-tracker with my app. The emitter and tracker are ok, but when i call the SelfDescribingJson the app crash.

```java
Map<String, String> attributes = new HashMap<>();
attributes.put("campaingID", "1");

SelfDescribingJson myContext = new SelfDescribingJson("iglu:myurlschema/jsonschema/1-0-0",
                attributes);
```

Error 

```
java.lang.VerifyError: com/snowplowanalytics/snowplow/tracker/utils/payload/SelfDescribingJson
at com.myapp.adBoard(ReportIVC.java:22)
```

my gradle

```
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:19.+'
    compile 'com.koushikdutta.ion:ion:1.+'
    compile 'com.google.android.gms:play-services:4.0+'
    compile 'com.github.satyan:sugar:+'
    compile 'com.squareup.retrofit:retrofit:1.6.1'
    compile 'com.squareup.okhttp:okhttp:2.0.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.0.0'
    compile 'com.snowplowanalytics:snowplow-android-tracker:0.3.0'
    compile 'com.netflix.rxjava:rxjava-core:0.+'
    compile 'com.netflix.rxjava:rxjava-android:0.+'
```

**Comment by jbeemster** [comment]
Hi @gianrubio, have not seen this error before personally but my first thought would be that there might be a missing dependency in your gradle file.  The `SelfDescribingJson` class is dependent on the following import:

https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-android-tracker/build.gradle#L71

Could you try adding that line and seeing if it will get you past that error?

**Comment by thiagogermoliato** [comment]
Hi @jbeemster, I am having the same problem, in my gradle file the import of Jackson JSON processor was already added.

java.lang.VerifyError: com/snowplowanalytics/snowplow/tracker/utils/payload/SelfDescribingJson

**Comment by jbeemster** [comment]
Hi @thiagogermoliato could you please paste the stack trace and your gradle build file and I will see if I can reproduce and resolve.

**Comment by httpheaders** [comment]
@thiagogermoliato I'm suspecting it's something related to conflicting versions of the Jackson JSON Processor on your classpath, maybe as a dependency for another library. Would help a lot to know what libraries you're using and  also to have a detailed stack trace as @jbeemster mentioned.

**Comment by MoizAli** [comment]
@gianrubio  did you solve this? I am getting the same issue.

**Comment by MoizAli** [comment]
@jbeemster  the problem is that the following two lines in my gradle file are conflicting as the jackson library is already added in the snowplow tracker 

compile 'com.snowplowanalytics:snowplow-android-tracker:0.3.0'
  compile 'com.fasterxml.jackson.core:jackson-databind:2.4.1.1'

**Comment by jbeemster** [comment]
Hey @MoizAli thanks for debugging that!  So if the conflicting dependency is updated the error goes away?

**Comment by jbeemster** [comment]
This is resolved now as the dependency has been removed from the library.
