### ISSUE TITLE
Gracefully handle lack of getAdvertisingIdInfo

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#118]
getAdvertisingIdInfo requires SDK 4.0+ which is not a good requirement to have in many countries, where developers are probably still supporting 2.3 for a bunch of old phones and tablets.

**Comment by jbeemster** [comment]
Apparently this had already been implemented by Jonathan but it appears in my merging and playing around with things it got removed.  So I have just reimplemented the old fix:

https://github.com/snowplow/snowplow-android-tracker/blob/c28be285add31c1b3ecfff0a40c7cf32b8e513d7/snowplow-android-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/android/Util.java#L61-L106

You can also now not import anything google related for those that are not interested in getting the advertising id.

**Comment by alexanderdean** [comment]
Nice!

**Comment by jbeemster** [comment]
I did get to learn a lot about Reflections though!  I had another question about this also, so if this function is run on the main thread it will throw an exception which is probably why Jonathan had a new thread being wrapped around it.  

Should I be chucking this function into Rx to ensure that this error does not occur?

**Comment by alexanderdean** [comment]
Up to you - sounds sensible though...

**Comment by jbeemster** [comment]
I will have a play with it and see what I can come up with..

**Comment by jonalmeida** [comment]
@jbeemster Hey! I been looking into something similar of late. I remember doing this after reading a conversation thread where Keen had solved the same problem from this codebase: https://github.com/adjust/android_sdk/blob/master/Adjust/adjust/src/main/java/com/adjust/sdk/Reflection.java

Although there might be nicer ways to do this now (at the cost of a dependency): https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability#isGooglePlayServicesAvailable%28android.content.Context%29

**Comment by jbeemster** [comment]
Ahh cool!  But I would imagine that even with that dependency we would still need to call all those functions via Reflection anyway with the same try/catch blocks.

**Comment by jonalmeida** [comment]
If you use `public int isGooglePlayServicesAvailable (Context context)`, I don't think you would need to make use of reflection then (see [this SO question](http://stackoverflow.com/questions/19715677/how-to-handle-if-user-needs-to-update-their-google-play-services)). 

Thinking about it more from the tracker context, reflection would be a better choice.
