### ISSUE TITLE
Document how to test instrumentation locally using Mountebank

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#120]

**Comment by alexanderdean** [comment]
Currently the Mountebank mocks are embedded in the test suite, so it's a bit hard to get started...

**Comment by jbeemster** [comment]
With the new testing setup with Ngrok and Mountebank this is all automated and there are instructions on how to get a local endpoint to send things to.  Does this need more explanation you think?

**Comment by jbeemster** [comment]
This is done.
