### ISSUE TITLE
Automatically set screen resolution?

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#132]
```
        WindowManager wm = (WindowManager) context.getSystemService(Context.WINDOW_SERVICE);
        Display display = wm.getDefaultDisplay();
        Point size = new Point();
        display.getSize(size);
        subject.setScreenResolution(size.x, size.y);
```

**Comment by alexanderdean** [comment]
A user is doing the above - is this better/different from what we are already doing? If so, how/why?

**Comment by jbeemster** [comment]
We are doing the same thing except that we are accounting for the fact that this only works on API 19 and up.  If we have a different target api it uses a different approach.

**Comment by alexanderdean** [comment]
Cool, closing
