### ISSUE TITLE
Core: add an event builder to simplify making events

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-android-tracker#133]

**Comment by jbeemster** [comment]
@alexanderdean for this ticket I was going to follow these examples for a builder with subclasses (https://weblogs.java.net/blog/emcmanus/archive/2010/10/25/using-builder-pattern-subclasses).  The usage would then be something like:

```java
tracker.track(PageViewEvent.Builder().url("").referer("").build())
```

PageViewEvent being an extended version of a base Event class which will have all the common event attributes.  Does this sound good to you or did you have something else in mind?

**Comment by alexanderdean** [comment]
I think that looks good @jbeemster ! It should be pretty user-familiar, user-friendly.
