### ISSUE TITLE
Update the geolocation context with a location listener

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-android-tracker#134]
Currently the geolocation gets set when the tracker is first created.. so it not really representative of the users location if they leave the application open and travel.  I think if we are going to have the option to collect this data it should be properly representative of the users location when the event gets sent.  Thoughts @alexanderdean ?

**Comment by alexanderdean** [comment]
Good question. It feels like something that should probably be updated on a timer in a background thread - e.g. every 5 minutes...

**Comment by jbeemster** [comment]
Agreed!  Ill update the title.

**Comment by shailesh17mar** [comment]
Hi, Is this enhancement added to the current version?

**Comment by jbeemster** [comment]
Hi @shailesh17mar, this update to how the geolocation context works will be updated in version 0.7.0 - two releases from now.

**Comment by jbeemster** [comment]
This should be implemented using a LocationListerner.  We can then configure updates based on:

1. Distance user moves (every 10 metres?)
2. Time based (every 5 minutes)

All can be configurable by the user.

**Comment by matus-tomlein** [comment]
Closing due to lack of priority
