### ISSUE TITLE
Core: deviceManufacturer not getting set if it is unavailable

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#135]
>  This morning I found a strange error in the Android tracker. It is raised for almost every event. The error is the following:

```json
{"level":"error","schema":{"loadingURI":"#","pointer":""},
  "instance":{"pointer":""},"domain":"validation","keyword":"required",
  "message":"object has missing required properties ([\"deviceManufacturer\"])",
  "required":["deviceManufacturer","deviceModel","osType","osVersion"],
  "missing":["deviceManufacturer"]
}
```

> I noticed that is was always raised by the same user by checking the idfa related to the events. Any idea of what could cause this?
> 
> It is not a critical error as it only concerns one user but it could be interesting to know if it is because of an other apk available on the web of a rooted Android version for example.

**Comment by jbeemster** [comment]
There could be a particular device that simply does not have a valid device manufacturer..  Could be that the user has rooted their phone or messed with something.  

I could update this field to populate itself as unknown if it cannot be found?  Or to not include the mobile context unless all required fields are included?

**Comment by jbeemster** [comment]
Actually we already have a check that it will be either be unknown or the manufacturer name.. Should not be possible for that field to be blank!  Will investigate...

**Comment by alexanderdean** [comment]
Thanks @jbeemster !

**Comment by jbeemster** [comment]
Okay so I initially read this section of code wrong, if we get an "unknown" manufacturer we simply leave this field blank.  Which is no good as it is a required field.

Are we happy to just populate this with unknown if we cannot get a proper manufacturer?

**Comment by alexanderdean** [comment]
Sounds good to me
