### ISSUE TITLE
Add a DEBUG and PRODUCTION mode to the Tracker

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-android-tracker#142]
Currently there are cases whereby the Tracker can throw an exception if the user is attempting to Track an event without having validated all of the Precondition checks for said event.  The idea is that in a DEBUG mode the Tracker would still throw these exceptions but in a Production environment would only log an error, preventing the Tracker from killing its host.

**Comment by AlexBenny** [comment]
Closing because recent versions (v2.0+) relies much less on Preconditions reducing the risk of invalidated events.
