### ISSUE TITLE
Perform blocking operations in the background

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-android-tracker#159]
Database creation should not be happening on the Main/UI Thread, in StrictMode creating the Emitter on this Thread throws many errors.

**Comment by jbeemster** [comment]
Pushing back as no clean way to do this..

**Comment by quiro91** [comment]
So is there no plan to work on this? Snowplow is the number 1 source of ANR in my app...

**Comment by BenFradet** [comment]
@quiro91 Unfortunately we haven't had a lot of cycles to dedicate to the trackers recently.
We're hoping to change that in the coming months 👍

**Comment by quiro91** [comment]
@BenFradet I hope so, this is honestly really bad and we will consider moving away from Snowplow if you're not even considering working on it

**Comment by quiro91** [comment]
It's been a while and I can see there's no progress about this. Do you think that initialising Snowplow on another thread would work as a workaround until a real solution is implemented?

**Comment by alexanderdean** [comment]
Re-assigning to @mhadam

**Comment by quiro91** [comment]
Any news about this?

**Comment by loopyzort** [comment]
I'd also like to know about this, as Snowplow is quickly climbing the charts as #1 source of ANRs in our app.
