### ISSUE TITLE
Gradle cannot find maven repo, unable to download Android Snowplow library

### ISSUE THREAD

**Issue by nasahapps** [snowplow/snowplow-android-tracker#167]
The Wiki says to put in your build.gradle file:  

`maven { url "http://maven.snplow.com/releases" }`  

But in doing so, Gradle hangs because it is unable to find this repo. And yes, I triple-checked to make sure "Offline work" is unchecked.  

Despite the fact that maven.snplow.com says "This repository is operational", it apparently isn't for Gradle.  

Running on Gradle 2.6, Android Studio 1.4 Beta 2.  

My suggestion? JCenter. Works fine for everyone else.

**Comment by jbeemster** [comment]
Hi @nasahapps, 

I have a sample project successfully getting the library from Maven.  I am however using the latest stable release of Android Studio not the beta; it feels like the beta may have introduced a bug with Maven potentially?

Would you be up for dropping your Android Studio back to the latest stable and seeing if it can find the repo then?

Current Versions:
- Android Studio 1.3.2
- Gradle 2.6

With buildscript dependency:
- classpath 'com.android.tools.build:gradle:1.3.0'

This is also the top-level gradle file I am using which is successfully allowing the library download:

```java
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
    }
}

allprojects {
    repositories {
        mavenCentral()
        jcenter()

        maven {
            url "http://maven.snplow.com/releases"
        }
    }
}
```

**Comment by nasahapps** [comment]
Still doesn't work. Used Android Studio 1.3.2/Gradle 2.6. Tested it both on a currently-existing project and a brand new project. Neither were able to pull from your maven repo. It just hangs on   

`> Configuring > 1/1 projects > Resolving dependencies ':app:_debugCompile'`  

However, if I comment this out  

```maven {  
    url "http://maven.snplow.com/releases"  
}```  

Then both projects (existing and new) are able to Gradle sync and build just fine.

**Comment by jbeemster** [comment]
Hey @nasahapps thanks for having a look at Android Studio 1.3.2.  Seems very strange that it won't resolve for you!  Out of curiosity would you mind posting your gradle files which fail to work?

We will have a look at getting the library onto JCenter regardless.

**Comment by nasahapps** [comment]
From my already-existing project:  

```java
apply plugin: 'com.github.ben-manes.versions'
buildscript {
    repositories {
        maven { url "https://raw.github.com/Raizlabs/maven-releases/master/releases" }
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
        classpath 'com.newrelic.agent.android:agent-gradle-plugin:5.3.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.7'
        classpath 'com.github.ben-manes:gradle-versions-plugin:0.11.3'
    }
}
allprojects {
    repositories {
        jcenter()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://raw.github.com/Raizlabs/maven-releases/master/releases" }
        maven { url "http://maven.snplow.com/releases" }
    }
}
// For disabled pre-dexing on CircleCI to improve build performance
project.ext.preDexLibs = !project.hasProperty('disablePreDex')
subprojects {
    project.plugins.whenPluginAdded { plugin ->
        if ("com.android.build.gradle.AppPlugin".equals(plugin.class.name)) {
            project.android.dexOptions.preDexLibraries = rootProject.ext.preDexLibs
        } else if ("com.android.build.gradle.LibraryPlugin".equals(plugin.class.name)) {
            project.android.dexOptions.preDexLibraries = rootProject.ext.preDexLibs
        }
    }
}
task wrapper(type: Wrapper) {
    gradleVersion = '2.6'
}
```  

From a brand new project:  

```java
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
    }
}
allprojects {
    repositories {
        jcenter()
        maven { url "http://maven.snplow.com/releases" }
    }
}  

These are for these projects' project build.gradle files. It doesn't matter about the individual module's build.gradle because regardless if I'm getting the actual Snowplow library or not, Gradle can't resolve Snowplow's maven repo.  

And thanks, I (as well as many others) would greatly appreciate it if the library was on jcenter or at the very least MavenCentral.

**Comment by 0xABAB** [comment]
I experience the exact same issue for the following (Gradle): 

```
allprojects {
  apply plugin: 'idea'
  apply plugin: 'eclipse'
  apply plugin: "jacoco"

  repositories {
    mavenCentral()

    maven {
      url "http://maven.snplow.com/releases"
    }
   // much more here
}
 
project (':whatever'){
    compile 'com.snowplowanalytics:snowplow-scala-tracker:0.2.0'
}
 ```

Since this has already been open since September 2015, can you fix this **ASAP**? 

I also think it would be reasonable if I would be able to browse http://maven.snplow.com/releases. Instead of just seeing: 

```
This repository is operational

All assets should be available at their dedicated paths
```

I don't have any means to check whether *anything* is actually there.

**Comment by ninjabear** [comment]
Hey @0xABAB!

Your sample `build.gradle` is for the scala tracker - if this is intended the dependency isn't quite right as gradle doesn't automatically resolve cross compiles for you (as sbt does with `%%`).

Here's a sample:

```{groovy}
apply plugin: 'scala'

repositories {
    mavenCentral()
    jcenter()
    maven { url "http://maven.snplow.com/releases/" }
}

dependencies {
    compile 'org.scala-lang:scala-library:2.11.6'
    compile 'com.snowplowanalytics:snowplow-scala-tracker_2.11:0.2.0'
}
```
The dependency is available here http://maven.snplow.com/releases/com/snowplowanalytics/snowplow-scala-tracker_2.11/0.2.0/snowplow-scala-tracker_2.11-0.2.0.pom

**Comment by ninjabear** [comment]
As a general update on the move to jcenter - we're actually in the process of moving all our libraries to jcenter & mavencentral. This tracker will be included soon!
