### ISSUE TITLE
Move hosting to JCenter

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#172]

**Comment by alexanderdean** [comment]
Currently a release of this tracker takes me about 80 minutes if there are no issues.

**Comment by jbeemster** [comment]
It's insanity... I think I can also do some updates to how it is built and tested without using an emulator.  Could speed things up.

**Comment by jbeemster** [comment]
Pending @ninjabear work on CI/CD

This should go into JCenter not Maven.

**Comment by alexanderdean** [comment]
Bringing forwards

**Comment by jbeemster** [comment]
Hey @alexanderdean, could you provide any extra details on the exact artifacts that need to be published for this?

**Comment by alexanderdean** [comment]
This was the manual steps, if it helps:

Because Travis doesn't work with Android yet, you should run the test suite locally first, as per the instructions in the README:

https://github.com/snowplow/snowplow-android-tracker#quickstart

Tests passed? Now:

```
guest$ ./gradlew publish
```

You will find the files in:

    snowplow-android-tracker/snowplow-android-tracker-classic/build/repo/com/snowplowanalytics/snowplow-android-tracker-classic/VERSION
    snowplow-android-tracker/snowplow-android-tracker-rx/build/repo/com/snowplowanalytics/snowplow-android-tracker-rx/VERSION
    
Copy these to the DropBox folder.

You also need to take the file:

    snowplow-android-tracker/snowplow-android-tracker-classic/build/outputs/aar/snowplow-android-tracker-classic-release.aar
    snowplow-android-tracker/snowplow-android-tracker-rx/build/outputs/aar/snowplow-android-tracker-rx-release.aar

And add it into your VERSION folder as:

    snowplow-android-tracker-{classic|rx}-VERSION.aar

**You need to do the same for the core too**

    snowplow-android-tracker/snowplow-android-core/build/outputs/aar/snowplow-android-core-release.aar

As:

    snowplow-android-core-VERSION.aar

Then upload to maven.snplow.com etc.

**Comment by jbeemster** [comment]
This should be a lot simpler now that we only have a single binary!  Could you also please upload the creds for me into travis so I can start work on this first thing tomorrow?

**Comment by jbeemster** [comment]
This is done automatically from Bintray...

**Comment by alexanderdean** [comment]
Nice!
