### ISSUE TITLE
Consider using GcmNetworkManager for scheduling events

### ISSUE THREAD

**Issue by jonalmeida** [snowplow/snowplow-android-tracker#174]
Hey Josh,

I came across the [GcmNetworkManager](https://developers.google.com/android/reference/com/google/android/gms/gcm/GcmNetworkManager) which might be helpful for batching network operatons and auto back-off when sending tracking events - thought you might find it helpful.

One downside is that it makes use of Google Play Services though.

The reference video is easier to consume: [here](https://www.youtube.com/watch?v=nDHeuEM30ks).

**Comment by jbeemster** [comment]
It very well might be useful.  It is a shame it requires Play Services though as we just managed to chop that out to make the DEX limit a bit more manageable.

I might just steal the ideas that they have shared for sending events in my own wrapper though.  They do raise a lot of good points for when we should be sending data.

Thanks for the info!

**Comment by jonalmeida** [comment]
GNM uses a [JobScheduler](https://developer.android.com/reference/android/app/job/JobScheduler.html) under the hood (which is only available in 5.0), but there is a [compat version](https://github.com/evant/JobSchedulerCompat) that isn't maintained anymore which you might find useful.

Good luck!

**Comment by AlexBenny** [comment]
GcmNetworkManager is deprecated. Evaluate WorkManager instead. It can be useful in case of an Emitter refactoring. https://developer.android.com/topic/libraries/architecture/workmanager
