### ISSUE TITLE
Convert removal of events from database into a single query

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-android-tracker#177]
Currently we are doing hundreds of queries into the database to just delete where they could all be nested into one call.

Should work something like this: https://github.com/snowplow/snowplow-unity-tracker/blob/master/SnowplowTracker/SnowplowTracker/Storage/EventStore.cs#L158-L175

**Comment by alexanderdean** [comment]
Is this a bug? If not, would rather wait till 0.6.0

**Comment by jbeemster** [comment]
It is not technically a bug no but it is very inefficient.  Will push it back!

**Comment by alexanderdean** [comment]
Thanks @jbeemster - generally in a patch release we only want bug fixes, ideally ones which can be **visually verified** to not break anything.
