### ISSUE TITLE
Add network_type and network_technology to mobile_context

### ISSUE THREAD

**Issue by bernardosrulzon** [snowplow/snowplow-android-tracker#179]
Unlike its iOS counterpart, the Android tracker doesn't fill the network_type and network_technology columns on mobile_context. It would be super helpful to see how Wifi and 3G connections influence user behaviour/engagement.

**Comment by bernardosrulzon** [comment]
This is a good reference: https://gist.github.com/emil2k/5130324

**Comment by jbeemster** [comment]
Closing as duplicate of https://github.com/snowplow/snowplow-android-tracker/pull/180

**Comment by bernardosrulzon** [comment]
@jbeemster #179 is the issue, #180 is the PR

**Comment by jbeemster** [comment]
@bernardosrulzon we reference the PR as the issue in the CHANGELOG generally.  I will take the code from the PR and merge it as a new commit which closes the PR when we pull it across to master.

**Comment by bernardosrulzon** [comment]
ah - that makes a lot of sense. thanks!
