### ISSUE TITLE
Create an FAQ for Android documentation

### ISSUE THREAD

**Issue by jonalmeida** [snowplow/snowplow-android-tracker#18]
With Android there are several occasions where you can ask, why is this happening? So we can add an FAQ section to counter these:

Here is an initial list of things to document in it:
- [ ] Add permissions for INTERNET
- [ ] Crashing when using `Subject` with `Context` but not adding Play Services
- [ ] Project module not recognized (See: #10)
- [ ] Make sure java-core is updated to the right version

**Comment by jbeemster** [comment]
I think this ticket can probably be closed now:
- Have added a note about adding permissions for INTERNET
- There is no more crashing

.. the other two I do not believe are related to this project anymore as we have diverged.

**Comment by alexanderdean** [comment]
Great please close!
