### ISSUE TITLE
Add ability for tracker to support multiple namespace:collector pairings

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#181]
Sister ticket of https://github.com/snowplow/snowplow-objc-tracker/issues/115

Related to #175

**Comment by jbeemster** [comment]
Moving this back as it is a very big change which should be in a smaller milestone to avoid introducing bugs.

**Comment by AlexBenny** [comment]
Closing as implemented as part of the upcoming version 2.0.
More details in this ticket: #426
