### ISSUE TITLE
Remove RxJava and merge Classic into core

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-android-tracker#187]
As we have been able to achieve the same performance with a classic Java concurrent approach the RxJava branch of this tracker does not really bring anything useful anymore.  It adds complexity and a huge amount of functions to the DEX limit.  As well as requiring us to have three distinct libraries.

From the point of view of code management and deployment it would make a lot of sense to deprecate RxJava and merge the Classic Tracker with core. 

Thoughts @alexanderdean ?

**Comment by alexanderdean** [comment]
Love it, agree
