### ISSUE TITLE
Util.getAdvertisingId(Context) e.getCause() can be null

### ISSUE THREAD

**Issue by michaelayates** [snowplow/snowplow-android-tracker#191]
Whilst writing some tests for our usage of the Android tracker I've come across an issue.

In the test environment (and presumably in quite a few real environments) it is possible the class om.google.android.gms.ads.identifier.AdvertisingIdClient doesn't exist.

The type of Exception thrown in this case is:
java.lang.ClassNotFoundException: com.google.android.gms.ads.identifier.AdvertisingIdClient

This exception (at least in my test environment) does not carry a cause.
Therefore e.getCause() on line 220 here
https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-android-core/src/main/java/com/snowplowanalytics/snowplow/tracker/utils/Util.java#L220

Causes a null pointer exception.
Subsequent code seems to handle the null return value from getAdvertisingId 

So I suggest the log line be updated to something like
Logger.e(TAG, "Exception getting the Advertising ID: %s", e.toString());

**Comment by alexanderdean** [comment]
Thanks for spotting this @michaelayates !

**Comment by MoizAli** [comment]
Is this fixed?

**Comment by jbeemster** [comment]
Hi @MoizAli this has been scheduled to be fixed in the next release
