### ISSUE TITLE
Stop incrementing SessionIndex while application in background

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-android-tracker#192]

**Comment by jbeemster** [comment]
Hey @alexanderdean how should this state be handled exactly.  Should we just shut the Session thread down when we go into the background and resume it when we are in the foreground again?  The restart would then force it to increment by 1. 

This however presumes that a loss of focus, however long, is the end of a session.

In some applications there might be situations where a link prompts the opening of another application which is then used, before the user returns to the calling app.

**Comment by alexanderdean** [comment]
Could you put some options in a Markdown table in this ticket for us to discuss?

**Comment by jbeemster** [comment]
So essentially the issue is that if an application is sent to the background and not resumed for a large length of time the Session keeps expiring over and over again.  This occurs because the application is still alive just not in focus.

Applications are often dropped to the background for a number of reasons:
- Incoming phone call
- Interactive intent from one app which launches another (Sharing a URL to Messenger)

These events do not mean that the user has finished their session as such but rather have been distracted temporarily (potentially).

To ensure we do not prematurely end the Session I would suggest we allow the Session to go into the background but if the Session expires in the background we then stop checking for Session expiration until we are brought back into the Foreground.

**Comment by alexanderdean** [comment]
Sessionization on foregrounding/backgrounding, feel free to edit:

|                      | Pros              | Cons                                                           |
|----------------------|-------------------|----------------------------------------------------------------|
| Pause sessionization | Simple to explain | A session can last an arbitrary length of time (in background) |
| Terminate session    | Simple to explain | A session ends even if just a temporary URI open or similar    |
| ???                  | ???               | ???                                                            |

**Comment by alexanderdean** [comment]
ccing @yalisassoon and @bogaert for feedback...

**Comment by bogaert** [comment]
I think we can drop option 1. If a session can last an arbitrary length of time, knowing number of sessions becomes less useful.

That leaves options 2 and 3. I would go with option 3, because option 2 is a special case of 3 (background timeout set to 0). That is if there are no issues implementing this.

Is it now possible, just looking at the event stream, to determine when an app was sent to the background and/or foreground? This would make it possible to measure the time between the last and the first foreground event – allowing our users to determine the proper background timeout, and study how users interact with the app (lots of quick interactions, or long and uninterrupted sessions).

**Comment by jbeemster** [comment]
I think option 3 gives us the best set of information and yes @bogaert exactly that.  We are going to track all of the foreground and background events which can then help figure out a lot of the session interaction.

**Comment by alexanderdean** [comment]
Nice, I like the point that option 2 is a special case of 3.

Automatic backgrounding/foregrounding will come in 0.6.0 in this ticket: https://github.com/snowplow/snowplow-android-tracker/issues/206

**Comment by bernardosrulzon** [comment]
Good discussion - I agree with option 3 as well. Looking forward to this release, it will be a very welcome improvement on the way we look at sessions on Android!
