### ISSUE TITLE
Snowplow Android not send events

### ISSUE THREAD

**Issue by delmanoPedro** [snowplow/snowplow-android-tracker#199]
I have a problem with the Snowplow Android Tracker.

I create the events call and checking my log it works fine, but the Snowplow not send the events for my back end. 

I look the Snowplow database and it is populate right.

Follow my code when I build the emitter and tracker.
`private Emitter buildEmitter() {
        return new Emitter
                .EmitterBuilder(emitterUrl, getContext())
                .method(HttpMethod.GET)
                .security(RequestSecurity.HTTP)
                .tick(2)
                .timeUnit(TimeUnit.MINUTES)
                .callback(callback)
                .build();
    }
`
   ` private Tracker buildTracker() {
        Tracker tracker = new Tracker
                .TrackerBuilder(buildEmitter(), "br.digitalpages.com.br/mobile", getAppId(), getContext())
                .base64(false)
                .platform(DevicePlatforms.Mobile)
                .level(LogLevel.VERBOSE)
                .build();
        return tracker;
    }
`

I wonder if anyone can help me ?

Thanks!

**Comment by jbeemster** [comment]
Hi @delmanoPedro what specific version of the Android Tracker are using?
Is the callback method you are providing firing?

**Comment by delmanoPedro** [comment]
HI @jbeemster I'm using the 0.5.4 of the snowplow classic tracker.

I included the callback but it not called and I connect the Charles proxy and check if my events is hiring, but not was sent.

**Comment by jbeemster** [comment]
Hi @delmanoPedro could you please post this question to our [discourse](http://discourse.snowplowanalytics.com/) page.

**Comment by delmanoPedro** [comment]
Ok @jbeemster thanks for help!
