### ISSUE TITLE
Add ability to automatically fetch the IP Address

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-android-tracker#200]

**Comment by alexanderdean** [comment]
What does this one mean @jbeemster ?

**Comment by jbeemster** [comment]
Its quite difficult to get this value for the Subject class so it might be nice to have a utility function for this.

**Comment by alexanderdean** [comment]
Are we thinking about the same thing? Our collectors can pick up the IP address of the user super-easily.

**Comment by jbeemster** [comment]
Oh yeah true.. at the Android side its hard but the collectors do get it easy!

**Comment by alexanderdean** [comment]
Yep, this isn't a priority...
