### ISSUE TITLE
Placeholder for some kind of automatic event sending

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#201]
Adding some kind of auto-event tracking, maybe something like automatically sending a screen view, maybe Fragment and Activity views.

Let's try and come up with something simple that adds some value, and we can iterate from there!

**Comment by jbeemster** [comment]
Other simple ideas:
- Application open
- Application pause

We could also see if we could build something akin to what Crashlytics (Fabric.io) have which creates a hook for any fatal exceptions that crash the application.  Being able to see what crashes happened in your app is hugely important - seeing the crashes with all the other contextual information we can grab means they can actually be fixed.

**Comment by alexanderdean** [comment]
@jbeemster - the Crashyltics idea is awesome. I've been meaning to talk to you about this. Getting well constructed Android and Objective-C crash reports into Snowplow would be a huge win. (I've also been looking at what it would take for us to build an enrichment to lookup the Objective-C crash report data - see https://github.com/snowplow/snowplow/issues/2733).

Could you create a separate ticket for the fatal exceptions tracking?

**Comment by jbeemster** [comment]
Descheduling for the moment as we might come up with some other ideas in the future...

**Comment by AlexBenny** [comment]
Closing as we have already automatic event sending about ScreenView, lifecycle events and crash reporting.
