### ISSUE TITLE
Automatically track activity resume/pause lifecycle events

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-android-tracker#206]

**Comment by alexanderdean** [comment]
@jbeemster - can you update this ticket based on what we've learnt/discussed?

**Comment by alexanderdean** [comment]
Please add a link to the Iglu Central ticket too

**Comment by dcow** [comment]
@jbeemster I'm using `0.6.0` with `lifecycleEvents(true)` and I don't see anything coming through.

**Comment by jbeemster** [comment]
Hi @dcow could you please post this to our [discourse forum](http://discourse.snowplowanalytics.com/) for help on getting features working.  We use GitHub solely for bug and feature tracking.
