### ISSUE TITLE
Update the demonstration app

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-android-tracker#214]
The demo app as it stands is very basic in that it is only able to send a flat collection of events with little in the way of user interaction.  It would be useful from a testing perspective to:
- Allow the user to change all the currently available settings for the various parts of the tracker
  - Gives us a visual representation of the API and its capabilities
- Define and send custom events in the demo app
  - Custom SelfDescribing Jsons
  - Custom input into our predefined events
- Publish the app to the play store so we have better vision on:
  - Required proguard settings for integrating the Tracker into other apps
  - Much easier for users to download and test the SDK before moving towards integration
  - Much better example of how to use the SDK in an actual application

This would allow us to have a fully defined demo of the SDK which lets users see the full event stream from the Tracker including our new automated events.

Thoughts @alexanderdean ?

**Comment by alexanderdean** [comment]
Sounds good - scheduling!

**Comment by jbeemster** [comment]
Should we extend this over to iOS as well?

**Comment by alexanderdean** [comment]
Let's create a companion ticket!

**Comment by jbeemster** [comment]
Related to: https://github.com/snowplow/snowplow-android-tracker/issues/198

**Comment by jbeemster** [comment]
Another idea would be to have the ability to sync the app with your public iglu repository so you could then easily send custom dummy events to an endpoint to validate that your schemas are correct.

**Comment by alexanderdean** [comment]
Cool idea!

**Comment by matus-tomlein** [comment]
We now have a JetPack Compose demo which is more interesting than the demo app. Closing the issue for now.
