### ISSUE TITLE
Android app doesnt compile with tracker 0.6.0

### ISSUE THREAD

**Issue by shailesh17mar** [snowplow/snowplow-android-tracker#218]
What am I missing here. 
dependencies {
    ...
    compile 'com.snowplowanalytics:snowplow-android-tracker:0.6.0@aar'
}

**Comment by jbeemster** [comment]
Hi @shailesh17mar it has not been released as of yet.  It is still in review process.  If you want to get started asap please use:

```
dependencies {
...
compile 'com.snowplowanalytics:snowplow-android-tracker:0.6.0-M1@aar'
}
```

**Comment by shailesh17mar** [comment]
I tried this version as well. Gradle sync is successful but, I cannot reference anything from library inside my application.

**Comment by jbeemster** [comment]
Do you also have: `compile 'com.squareup.okhttp3:okhttp:3.4.1'` in your dependencies?

**Comment by shailesh17mar** [comment]
was using okhttp2.1 before. Even after changing it to 3.4.1 nothing happened.
 compile 'com.squareup.okhttp3:okhttp:3.4.1'

    compile 'com.snowplowanalytics:snowplow-android-tracker:0.6.0-M1@aar'

**Comment by jbeemster** [comment]
Hi @shailesh17mar, could you also try adding:

```groovy
compile 'com.android.support:support-v4:24.2.0'
compile 'com.android.support:appcompat-v7:24.2.0'
```

**Comment by shailesh17mar** [comment]
@jbeemster Still same issue
`   compile 'com.android.support:support-v4:24.2.0'
    compile 'com.android.support:appcompat-v7:24.2.0'
    testCompile 'junit:junit:4.12'

    compile 'com.google.android.gms:play-services-location:9.4.0'

    compile 'com.google.android.gms:play-services-analytics:9.4.0'

    compile 'com.squareup.okhttp3:okhttp:3.4.1'

    compile 'com.snowplowanalytics:snowplow-android-tracker:0.6.0-M1@aar'`

**Comment by jbeemster** [comment]
@shailesh17mar very strange!  I am going to publish an M2 later today with a much cleaner dependency (removing support and appcompat from the library).  I will ping you when it is available.

However in my own testing in two separate apps the resolution seems to be working just fine.  Perhaps try removing the `@aar` from the compile line?

**Comment by shailesh17mar** [comment]
@jbeemster Please do that. Yeah it is strange. I tried everything and previously I had tried with 0.5.4 and it was working fine but I needed Geolocationcontext and Mobilecontext enabled in Tracker therefore, I tried 0.6.0 and since then I am stuck. I will give it a fresh look again but, do publish M2 later and ping me if its not much trouble for you.  Thanks you guys have an active community. :)

**Comment by jbeemster** [comment]
Hey @shailesh17mar the -M2 has now been published and only has a dependency on the OkHTTP library.  So if you could try again by both:

```
compile 'com.squareup.okhttp3:okhttp:3.4.1'
compile 'com.snowplowanalytics:snowplow-android-tracker:0.6.0-M2@aar'
```

and

```
compile 'com.squareup.okhttp3:okhttp:3.4.1'
compile 'com.snowplowanalytics:snowplow-android-tracker:0.6.0-M2'
```

That would be a great help!

**Comment by shailesh17mar** [comment]
First I tried with your new SDK and it still didnt work. Then, suspecting that now something must be wrong with this god forsaken Android Studio I commented my entire codebase wherever I had used Snowplow and then gradle synced and when I started uncommenting code it started showing me intellisense for snowplow classes. Wasted entire day.

**Comment by jbeemster** [comment]
@shailesh17mar glad to hear it is all working again!  Android Studio can be very frustrating sometimes... I feel your pain.

**Comment by shailesh17mar** [comment]
@jbeemster Thanks man for your time. :)
