### ISSUE TITLE
Thought: adding the macAddress of the NICs to the mobile context

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-android-tracker#219]
This would potentially allow us to:
- Have a user uninstall
- Have a user reinstall and be able to stitch the information back together

Mac addresses generally do not change unless the user actively spoofs it.  However it is not guaranteed to be unique to a particular user so might not be 100% accurate in stitching it backwards.

http://stackoverflow.com/questions/11705906/programmatically-getting-the-mac-of-an-android-device

Thoughts @alexanderdean ?

**Comment by alexanderdean** [comment]
> Getting the MAC address through WifiInfo.getMacAddress() won't work on Marshmallow and above

?

**Comment by jbeemster** [comment]
Ahh damn did not read through all of it!  Looks like from 6.0+ it is disabled through normal channels...

Looks like someone found a workaround though: http://stackoverflow.com/questions/33159224/getting-mac-address-in-android-6-0/37979584#37979584

**Comment by jbeemster** [comment]
Another workaround: http://stackoverflow.com/a/35830358

**Comment by AlexBenny** [comment]
Closing because increased privacy concerns can make it hard to achieve on mobile devices.
Please, feel free to reopen or comment this issue, whether it's of your interest or you want to contribute on this.
