### ISSUE TITLE
Add support for multiple emitters

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#221]
Per https://groups.google.com/forum/#!topic/snowplow-user/6ELjJPGRPjU

Child of https://github.com/snowplow/snowplow/issues/2867

**Comment by AlexBenny** [comment]
Closing as part of the upcoming version 2.0.
It allows the multiple trackers with different emitter configuration. It doesn't allow to track the same event on multiple emitter straightaway. The same event has to be tracked on each tracker configured.
Future iteration on this topic will provide a better solution to ease this problem off.
See issue #426
