### ISSUE TITLE
Update documentation with a strong warning when setting event ID

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow-android-tracker#222]
Some users are setting a custom event ID, and as a result generating lots of duplicates. Let's update the documentation with:
- a strong warning that this should only be used rare cases (if done wrong, the data will be hard to consume)
- some example use cases

**Comment by alexanderdean** [comment]
Assigning to @jbeemster - the main use case for setting your own event ID is when you want to emit events into two systems (maybe two Snowplows, or a Snowplow and another analytics system) and you want to be able to reconcile them later.

**Comment by AlexBenny** [comment]
Closing as the upcoming version 2.0 doesn't allow the setting of the event ID.

Using the event ID to uniquely identify the event in the pipeline and uniquely identify the event in the user domain can be dangerous as it's not guaranteed that this two domains match perfectly. In the version 1.x of the tracker many events could be sent with the same event ID causing severe issues in deduplication phase.
For this reason the event ID is only set by the tracker and the user can't change it.
In case you want to track the same event using a common ID, you should use a custom context with a custom generated ID.

Future iterations on this topic will be done to ease this problem off.
See issue #422
