### ISSUE TITLE
Setting `lifecycleEvents(true)` but no events are fired

### ISSUE THREAD

**Issue by dcow** [snowplow/snowplow-android-tracker#223]
I'm on `0.6.0` and using `lifecycleEvents(true)` however I don't see any foreground/background events coming through. I have my own componentCallbacks and I'm able to replicate the expected behavior (i.e. my object receives the expected memory trim callbacks).

**Comment by jbeemster** [comment]
Hi @dcow have you made sure to set the `lifecycleHandler` for the Tracker?

https://github.com/snowplow/snowplow/wiki/Android-Tracker#set-lifecycle-handler

If this is not done then the Tracker will not be able to send `lifecycleEvents` as their is no calling handler.

**Comment by dcow** [comment]
@jbeemster I suspect that's the issue. Thanks.

**Comment by jbeemster** [comment]
In future please post these types of questions to Discourse, as I said in the other ticket we try to keep Github for actual issues and bugs.

**Comment by dcow** [comment]
@jbeemster I thought this was a bug considering my own callbacks were called. Perhaps it suggests the api could be made more clear. The tracker builder accepts a context in it's constructor there really isn't a reason I should expect that I need to provide another one after it's built. That was my thinking anyway...
