### ISSUE TITLE
Make tracker.setLifecycleHandler take a Context instead of an Activity

### ISSUE THREAD

**Issue by dcow** [snowplow/snowplow-android-tracker#224]
It's common to setup your tracker to live with the application and so an Application context is the only thing available. The `setLifecycleHandler` method takes an Activity restricting its use to activities.

The method does:

```
if((this.lifecycleEvents || this.sessionContext) && VERSION.SDK_INT >= 14) {
    LifecycleHandler handler = new LifecycleHandler();
    activity.getApplication().registerActivityLifecycleCallbacks(handler);
    activity.registerComponentCallbacks(handler);
}
```

activity.registerComponentCallbacks simply calls through to `getApplicationContext().register...`. So this method should be fine just accepting any context.

**Comment by dcow** [comment]
Furthermore, a tracker already has a context. This method seems superfluous.

**Comment by jbeemster** [comment]
I left it as `Activity` to allow for a single argument setup and because we need to grab the Activities application to actually register the handler.  Unless `registerActivityLifecycleCallbacks` can be used against a `Context`?

**Comment by dcow** [comment]
@jbeemster `registerActivityLifecycleCallbacks()` is a method on `Application`. You can always call `context.getApplication()`.

**Comment by jbeemster** [comment]
The `Context` object does not actually have a `getApplication()` function: https://developer.android.com/reference/android/content/Context.html

As such we need the Activity to get the Application to register the handler.

It is not superfluous as it is only needed for this particular feature... so I decided not to ask for it if it was not required.

**Comment by dcow** [comment]
Sorry `context.getApplicationContext()`.

**Comment by jbeemster** [comment]
There you go! Didn't know you could cast the applicationContext to an application.  If you have the time would love to see a PR with your proposed API changes.

**Comment by dcow** [comment]
Absolutely! Probably won't get to it today but hopefully next week.

**Comment by dcow** [comment]
This works too:

    class DummyActivity extends  Activity {
        DummyActivity() {
            super();
            attachBaseContext(SnowplowAnalyticsClient.this.context);
        }
    }
    tracker.setLifecycleHandler(new DummyActivity());

**Comment by dcow** [comment]
@jbeemster I'm blocked by #227

**Comment by colmsnowplow** [comment]
+1 from another user:

> Feedback on the sdk. It’s a tad annoying that `void setLifecycleHandler(Activity activity)` uses activity and not just android Context as it doesn’t seem to need anything more than that from reviewing your code

**Comment by alexanderdean** [comment]
Scheduling so we don't miss this

**Comment by dcow** [comment]
Nice!
