### ISSUE TITLE
Add a method to start a new session

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow-android-tracker#226]
Sessionization is now purely based on time since the last event. We could add a method that, if called, resets the session ID and increments the session index.

Possible use cases:
- a user switches accounts
- a user completes a purchase and returns to the homepage

See also: https://github.com/snowplow/snowplow-objc-tracker/issues/290

**Comment by jbeemster** [comment]
Hey @bogaert this can already be done in Android by:

1. Tracker.pauseSessionChecking()
2. Tracker.resumeSessionChecking()

The first function shuts down all session checking and the second restarts it, on resumption the session id is incremented.

**Comment by bogaert** [comment]
That's good to know.

I still think there's a case to be made to add a third function, perhaps something like `Tracker.startNewSession()`? There are 2 reasons:

1. The function name describes how it's expected to be used.

2. If a certain event occurs, e.g. a user completes a purchase and returns to the homepage, one would only need to call the one function rather than both function in quick succession.

I'm leaving it open for discussion now. There's some thinking we can do on sessionization in general.

**Comment by jbeemster** [comment]
Oh totally agree that we need another function.  Was just mentioning in case you had a pressing case for using something like this!
