### ISSUE TITLE
Ensure vagrant environment can build and test tracker

### ISSUE THREAD

**Issue by dcow** [snowplow/snowplow-android-tracker#227]
When I update the android sdk in the vagrant environment I run out of space. 

Should people be manually managing the sdk or should updated versions be checked into the configuration?

**Comment by dcow** [comment]
@jbeemster when I update the android sdk in the dev environment I run out of disk space.

**Comment by jbeemster** [comment]
Hey @dcow sorry for the lag on getting back to you with this one!  I have updated the Vagrant environment through our Ansible Playbooks system so everything should be working again for building within Vagrant.
