### ISSUE TITLE
Capture campaign attribution as mobile_install event

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow-android-tracker#235]
See: https://github.com/snowplow/snowplow-objc-tracker/issues/297

**Comment by bernardosrulzon** [comment]
@bogaert This would be nice :)

We have implemented an Install Referrer tracking for first time installs. Maybe it could be supported out of the box with Snowplow. Details in the docs: https://developers.google.com/android/reference/com/google/android/gms/tagmanager/InstallReferrerReceiver

**Comment by alexanderdean** [comment]
Hey @bernardosrulzon - could you flesh out how we would support this out of the box?

**Comment by bernardosrulzon** [comment]
The use case is to see which campaigns are generating app installs - these campaigns must have referrer params in the Google Play URL ([example](https://play.google.com/store/apps/details?id=br.com.getninjas.pro&referrer=utm_source%3Dgetninjas%26utm_medium%3Dsite%26utm_campaign%3Dhome)).

You can get the referrer information, after the user has downloaded the app, through the `INSTALL_REFERRER` broadcast. Then, these parameters would go into a `mobile_install` self-describing event, making it possible to see which campaigns have better engagement/sales/etc.

An important benefit for internal campaigns (e.g. e-mail marketing asking your users to download the app) is that you could pass the user id into `utm_term`, making it possible to identify users before they ever log in.

**Comment by alexanderdean** [comment]
Awesome - thanks for sharing! Updating the ticket name...

**Comment by matus-tomlein** [comment]
We will implement the Play install referrer context entity in issue #249
