### ISSUE TITLE
Mobile context: offline events not being recorded as such

### ISSUE THREAD

**Issue by bernardosrulzon** [snowplow/snowplow-android-tracker#239]
Hey @jbeemster!

We've just implemented 0.6.1 and noticed an odd behaviour with offline events. I switched to airplane mode on the phone, then generated some events; when connection was resumed, `networkType` was passed as `wifi` rather then `offline` or `null` as I would expect.

Is this the intended behaviour?

**Comment by jbeemster** [comment]
Hey @bernardosrulzon!

The mobile and geolocation contexts have always been cached when the Tracker gets created.  The change with this release however is that the Tracker is a singleton and these contexts no longer get refreshed.

There are tickets to address this in 0.7.0 to put them both on configurable timers to ensure they get refreshed at intervals.  https://github.com/snowplow/snowplow-android-tracker/issues/220

On thinking about this though really we just need to re-get any information that could have changed and cache the rest - I was a bit too greedy caching everything!

Will see what I can do about getting a patch out for this.

**Comment by bernardosrulzon** [comment]
@jbeemster Ah, that would be awesome! I hadn't noticed that geolocation was also cached - this will be cool to see how users interact with the app while they're on the go!

**Comment by bernardosrulzon** [comment]
@jbeemster Thanks!!! Does this also solve the issue with geolocation you mentioned?

**Comment by bernardosrulzon** [comment]
Ah, nevermind! Just seen your post on discourse
