### ISSUE TITLE
set header property to Emitter

### ISSUE THREAD

**Issue by vishvendraa** [snowplow/snowplow-android-tracker#248]
Hi,

I am using local collector server and i have to add header value to the url ([{"key":"Raw-Request-URI","value":"http://localhost:8080","description":""}])
Please help me how to do that.

**Comment by alexanderdean** [comment]
Hi @vishvendraa - what happens if you don't set this header value?

**Comment by vishvendraa** [comment]
Thanks for reply @alexanderdean 
Actually the problem is 
I am trying to send data to collector that is on my local machine and i don't get any logs on collector. 
Emitter emitter = new Emitter.EmitterBuilder("172.xx.xx.80:8080", context)

**Comment by alexanderdean** [comment]
Can you raise on our forums please? https://discourse.snowplowanalytics.com/
