### ISSUE TITLE
Reset firstId even if app is in the foreground

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow-android-tracker#257]
`firstId` are only reset if the app is in the background:

https://github.com/snowplow/snowplow-android-tracker/blob/b702375c004dad67da84ffd9961c486e3435aaa0/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/Session.java#L140-L147

which causes subsequent foreground sessions to have the same `firstId`

**Comment by BenFradet** [comment]
c.f. #192

**Comment by alexanderdean** [comment]
Ouch good catch, thanks for scheduling

**Comment by BenFradet** [comment]
and c.f. https://snowplow.zendesk.com/agent/tickets/8211
