### ISSUE TITLE
Automatically set timezone?

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#260]
The timezone in mobile app is set with `setTimezone` method as per wiki:

* Android: https://github.com/snowplow/snowplow/wiki/Android-Tracker#315-set-timezone-with-settimezone
* iOS: https://github.com/snowplow/snowplow/wiki/iOS-Tracker#36-set-timezone-with-settimezone

Should there be an option to set the timezone automatically?

**Comment by mhadam** [comment]
In the Android tracker, this is already done(the device timezone is set as the default in the builder):
https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/Subject.java#L85

**Comment by alexanderdean** [comment]
Thanks for clarifying @mhadam! Closing
