### ISSUE TITLE
Add custom HTTP headers configuration

### ISSUE THREAD

**Issue by Stonepaw** [snowplow/snowplow-android-tracker#276]
I would like to add a custom header to outgoing events but I don't see a way to add that to the emitter. Is this supported or could be supported?

**Comment by alexanderdean** [comment]
What would be the purpose of this downstream in Snowplow?

**Comment by Stonepaw** [comment]
We would be passing in an authentication header to ensure only authenticated clients can send events.

**Comment by alexanderdean** [comment]
It's a neat idea - we are working on an "authenticated events" RFC but no specific plans around how we would implement this at this time (whether it would be headers or an update to the Snowplow Tracker Protocol).

**Comment by Stonepaw** [comment]
Will it be possible any time soon to add custom headers?

I cannot add it in my client because:
- The okHttpClient is private and I cannot add an interceptor to add headers to every request
- I cannot subclass Emitter in order to manipulate the list returned from buildRequests to add a header to any particular request.

**Comment by Stonepaw** [comment]
#269 Merging this PR will allow adding a header interceptor to the OkHttpClient which will solve this issue.

**Comment by AlexBenny** [comment]
Closing as it has been closed in the PR #269

**Comment by shalinibnair** [comment]
@Stonepaw , is it possible to add the custom header now. We are using react native tracker and need to send custom headers

**Comment by AlexBenny** [comment]
Hi @shalinibnair , at the moment that feature is not available directly in our react-native tracker. The custom headers can be added in the native trackers (which are wrapped by React Native tracker) but there isn't any specific configuration that lets the developer to set it in the React Native tracker. We (or you, if you prefer) can open an enhancement issue in the [react native tracker repository](https://github.com/snowplow/snowplow-react-native-tracker). It's not in our roadmap for this quarter but we may consider that feature for next release.

**Comment by AlexBenny** [comment]
@shalinibnair, I've just created the [issue](https://github.com/snowplow/snowplow-react-native-tracker/issues/165) in the react native repository. Feel free to continue the conversation there or add details for further improvements.
Thanks for raising this request.

**Comment by matus-tomlein** [comment]
Reopening this issue because it is a requested feature to add the ability to set custom headers and the approach to set a custom HTTP client is a bit awkward also because it changes the cookie jar. It would be better to have a an option in the `NetworkConfiguration` for it just like in the iOS tracker.
