### ISSUE TITLE
Add an upgrading guide from version 0.8 to 1.0 

### ISSUE THREAD

**Issue by benju69** [snowplow/snowplow-android-tracker#289]

**Comment by mhadam** [comment]
Is there any specific info you're looking for? If it's about the jump from 0.8 -> 1.0, we did that to address the impression that >1.0 isn't production ready.

**Comment by AlexBenny** [comment]
Closing as the migration guide has never been added for the version 1.0.
The upcoming version 2.0 will have a migration guide available in the official Snowplow docs. The link about the migration guide will be available in the README.md file of the repository.
