### ISSUE TITLE
Set emitter status when event store not instantiated

### ISSUE THREAD

**Issue by falcon4ever** [snowplow/snowplow-android-tracker#306]
Since our Android Tracker upgrade from 0.8.0 to 1.0.0 we've been missing Android session data in our system. I've been trying to track it down any breaking changes in the change logs but couldn't find anything.

With our current beta builds I've been testing 1.1.0 with verbose logging on and I've noticed that a fresh install of the app can have two different launch events. (Test device Pixel 3XL running Android 9)

**(1a)**
Successful launch:
```V/SnowplowTracker->Tracker: main|Tracker created successfully.
D/SnowplowTracker->Tracker: main|Session checking has been resumed.
D/SnowplowTracker->FileStore: pool-13-thread-2|Attempting to retrieve map from: snowplow_session_vars
D/SnowplowTracker->EventStore: pool-13-thread-1|DB Path: /data/user/0/com.xxx.xxx/databases/snowplowEvents.sqlite
V/SnowplowTracker->Util: pool-13-thread-1|Checking tracker internet connectivity.
E/SnowplowTracker->FileStore: pool-13-thread-2| + Exception getting vars map: /data/user/0/com.xxx.xxx/files/snowplow_session_vars (No such file or directory)
D/SnowplowTracker->Util: pool-13-thread-1|Tracker connection online: true
D/SnowplowTracker->Session: pool-13-thread-2|Session information is updated:
D/SnowplowTracker->Session: pool-13-thread-2| + Session ID: xxxxxxxx
D/SnowplowTracker->Session: pool-13-thread-2| + Previous Session ID: null
D/SnowplowTracker->Session: pool-13-thread-2| + Session Index: 1
D/SnowplowTracker->FileStore: pool-13-thread-2|Attempting to save: {sessionIndex=1, storageMechanism=SQLITE, firstEventId=null, sessionId=xxxxxxxx previousSessionId=null, userId=5c1c8711-5fa3-4157-b6b3-0d488a11737a}
E/SnowplowTracker->Emitter: pool-13-thread-1|Emitter database empty: 1
```

**(1b)**
With network call logs + messages like:
```
V/SnowplowTracker->Emitter: pool-13-thread-1|Processing emitter results.
D/SnowplowTracker->EventStore: pool-13-thread-1|Removed events from database: 2
D/SnowplowTracker->Emitter: pool-13-thread-1|Success Count: 2
D/SnowplowTracker->Emitter: pool-13-thread-1|Failure Count: 0
.
.
.
D/SnowplowTracker->Emitter: pool-13-thread-1|Request Futures: 1
V/SnowplowTracker->Emitter: pool-13-thread-2|Sending request: Request{method=GET, url=https://sp.wanderu.com/i?tnuid=78cb090......
```

**(2)**
Unsuccessful launch:
```V/SnowplowTracker->Tracker: main|Tracker created successfully.
D/SnowplowTracker->Tracker: main|Session checking has been resumed.
D/SnowplowTracker->FileStore: pool-12-thread-2|Attempting to retrieve map from: snowplow_session_vars
E/SnowplowTracker->FileStore: pool-12-thread-2| + Exception getting vars map: /data/user/0/com.xxx.xxx/files/snowplow_session_vars (No such file or directory)
D/SnowplowTracker->Session: pool-12-thread-2|Session information is updated:
D/SnowplowTracker->Session: pool-12-thread-2| + Session ID: ebc96fc0-3af6-4ddf-8fa3-0e42de52c3fd
D/SnowplowTracker->Session: pool-12-thread-2| + Previous Session ID: null
D/SnowplowTracker->Session: pool-12-thread-2| + Session Index: 1
D/SnowplowTracker->Emitter: pool-12-thread-2|Event store not instantiated.
```

The key seems to be `Event store not instantiated.` when that shows up on a launch, it won't be making any network calls.

There will just be a long list of:
```
D/SnowplowTracker->EventStore: pool-12-thread-1|Added event to database: 20
```

Relaunching the app (a few times?) sometimes helps to make it send the events stored in the database.

### Implementation details.

The tracker is instantiated from the `onCreate()` method of our `Application class` (written in Kotlin).

```
override fun setup(context: Context) {
    Log.d(mClassName, "Setup Snowplow using: " + context.getString(R.string.snowplow_url))

    val appName = context.getString(R.string.app_name).replace(" ".toRegex(), "_").toLowerCase() + "_android"
    Log.d(mClassName, "Setup Snowplow Tracker: " + appName)

    val emitter = Emitter.EmitterBuilder(context.getString(R.string.snowplow_url), context.applicationContext)
                            .security(RequestSecurity.HTTPS)
                            .method(HttpMethod.GET)
                            .callback(object : RequestCallback {
                                override fun onSuccess(successCount: Int) {
                                    logOnSuccessSnowplow(successCount)
                                }

                                override fun onFailure(successCount: Int, failureCount: Int) {
                                    onFailure(successCount, failureCount)
                                }
                            })
                            .build()

    val subject = Subject.SubjectBuilder()
            .context(context.applicationContext)
            .build()

    val tracker = Tracker.TrackerBuilder(emitter, BuildConfig.APPLICATION_ID, appName, context.applicationContext)
            .level(LogLevel.VERBOSE)
            .platform(DevicePlatforms.Mobile)
            .subject(subject)
            .sessionContext(true)
            .mobileContext(true)
            .lifecycleEvents(true)
            .screenContext(true)
            .installTracking(true)
            .applicationContext(true)
            .build()
    Tracker.init(tracker)
}
```

Events are added like this:
```
override fun trackEvent(se_category: String, se_action: String, se_label: String, se_property: String) {
    Log.d(mClassName, "Snowplow trackEvent: $se_category $se_action $se_label $se_property")

    Tracker.instance().track(
            Structured.builder()
                    .category(se_category)
                    .action(se_action)
                    .label(se_label)
                    .property(se_property)
                    .build()
    )
}
```

build.gradle
```
// Networking
implementation 'com.squareup.okhttp3:okhttp:3.14.1'

// Snowplow Android Tracker
implementation 'com.snowplowanalytics:snowplow-android-tracker:1.1.0@aar'
```

Any ideas why this is happening? Comparing Snowplow data with Firebase tracking there is a significant lower number of sessions. Snowplow reports 30~40% of what Firebase reports.

**Comment by thierryd** [comment]
I have the same problem. The issue comes from the fact that the Emitter never send event if `eventStore` is null (see Emitter.attemptEmit()). `eventStore` is null because when the Emitter is created, it is then instantiated asynchronously (see Emitter.java:270).

So because of a racing condition, sometimes eventStore() would get instanciated before attemptEmit(), sometimes not.

A workaround is to wait until the emitter has created the emiterStore before instanciated the Tracker:

```
while (emitter.eventStore == null) {
    SystemClock.sleep(100L)
}
```

**Comment by quiro91** [comment]
Any news about this? Happened to me too while upgrading from 0.8.0 to 1.0.1, had to revert the change

**Comment by mhadam** [comment]
This will be fixed in the coming release.

@thierryd's workaround is fine, or use `emitter.waitForEventStore()` after instantiating it.

**Comment by DavidSebestyen** [comment]
Hi guys, any estimate when this new update would be released?

**Comment by oguzhanunlu** [comment]
Hi @DavidSebestyen , we're working on finalizing the release work and expect to release sometime during next week, you can follow #310 in the meantime.

**Comment by SzotsLevente** [comment]
Guys any news about when this is gonna be released? by the way the workaround doesn't work, it's still sending for me way to many events not just one..

**Comment by oguzhanunlu** [comment]
Hi @SzotsLevente , we had to prioritize other projects' work for the last couple of weeks and we're sorry for the delay. We plan to publish 1.2.0 next week.

**Comment by SzotsLevente** [comment]
@oguzhanunlu this problem is still exist, i've tried it after the new release and it's still sending way too many events, any advice?

**Comment by oguzhanunlu** [comment]
Hi @SzotsLevente , we are sorry about it. We're aware of it and working on it. We'll publish a patch release to fix that and in the meantime you can use the workaround mentioned above.

**Comment by SzotsLevente** [comment]
workaround you mean 

> while (emitter.eventStore == null) {
    SystemClock.sleep(100L)
} this one? it doesn't help much, i've started it with this

**Comment by oguzhanunlu** [comment]
I was referring to [this comment above](https://github.com/snowplow/snowplow-android-tracker/issues/306#issuecomment-496290324).

**Comment by SzotsLevente** [comment]
i see, well i've put that right after the emitter is instantiated, that is where it should go right or where should i put it?

**Comment by oguzhanunlu** [comment]
Not sure about the workarounds mentioned, you may consider using 1.0.0 or older until we fix this.
