### ISSUE TITLE
Fix sending duplicate contexts

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow/snowplow-android-tracker#314]
`1.2.0` wasn't successful on leveraging global contexts.

**Comment by SzotsLevente** [comment]
@oguzhanunlu also please check custom context, it seems that it got broke in the process as well

**Comment by oguzhanunlu** [comment]
@SzotsLevente , do you refer to global contexts or plain custom contexts that we attach to events one by one? Do you mind sharing more details on what got broke in which process etc. Thanks!

**Comment by SzotsLevente** [comment]
custom context i mean by the set of data that is constructed using hashmap

**Comment by djohannot** [comment]
global context are broken, tou add to them without clearing anytime, so it never stop to grows. Also having global context that is modified by a third party thread (the executor) makes it veeeeeery dangerous and unreliable i think, you should check your code and add more unit test that are more aggressive with your implementation (do loop of event sending and add network delay, check the size of your global context growing, etc.)

**Comment by oguzhanunlu** [comment]
Hi @djohannot , thanks for the feedback, we are trying to improve our test suite. Could you provide us with more details on your global contexts usage? We'd like to see what is broken and fix it within the next release. Thanks in advance.

**Comment by YSDC** [comment]
Problem is the tracker contexts are added indefinitely (Mobile, location, session contexts etc). In our case we have a look of events created and as the global contexts are never cleared it keeps continue added them

**Comment by YSDC** [comment]
So even if I clear the global contexts before calling track it adds hundred of them

**Comment by YSDC** [comment]
In fact I don’t really see the gain of having the global contexts added in a list in each event. Should be a map to avoid adding duplicates. Don’t you think?

**Comment by oguzhanunlu** [comment]
Hi @YSDC , thanks for the feedback! Currently the tracker doesn't check if there are duplicate global contexts. We haven't introduced any safeguard in the initial release but will be improving the way global contexts are used.

Regarding that tracker adding multiple/hundreds of the same context, are you sure there is no custom context added to events manually in your SDK usage, or calling `addGlobalContext` in a loop etc.?

We can solve this issue a lot faster if we know how it happened. Do you mind sharing more details on your SDK usage so that we can reproduce the case and fix it? Thanks in advance.

**Comment by djohannot** [comment]
You are welcome. I add custom contexts to my events, but these are not the one that are duplicated. It's the one defined by snowplow. 

Also I never call `addGlobalContext,` i just call the `track(Event` event)` method, and in the tracker getFinal... it does it automatically. 

In attachment a picture of the decoded content of snowplow event

![Screen Shot 2019-07-22 at 14 31 17](https://user-images.githubusercontent.com/35487270/61626200-b34c5080-ac8d-11e9-9296-4dd2456a70e6.png)

**Comment by djohannot** [comment]
Sorry i switch between accounts :)

**Comment by oguzhanunlu** [comment]
Thanks @djohannot for the quick return. I've a question though.

Your [first comment above](https://github.com/snowplow/snowplow-android-tracker/issues/314#issuecomment-513662844) starts with `global context are broken` but then you wrote that `I never call addGlobalContext`. I'm a bit confused and would like to be on the same page. Did you want to refer to [the predefined contexts](https://github.com/snowplow/snowplow/wiki/Contexts-overview#predefined-contexts) that are natively supported by Snowplow (the ones that you can enable/disable through dedicated functions, e.g. `TrackerBuilder.geoLocationContext(true)`) instead of global contexts? Because the screenshot doesn't tell me that global contexts are broken. The problem appears to be with the predefined contexts. Using `clearGlobalContexts` without using `addGlobalContext` doesn't sound meaningful as well. Would you agree with me?

I'll try to reproduce the case and post my update here, whether I found the cause or couldn't reproduce etc.

**Comment by djohannot** [comment]
I hope i am wrong, let me explain you how i have implement it.
1) I have set some predefined context to true (session, mobile, etc.)
2) I create events in a loop, and for each of them i add custom context (the one hidden in black on the previous picture)
3) in this loop, when the event is created, i call track
4) in Tracker.java it enters `Executor.execute` that will call `addEventPayload` that will call `getFinalContext`
5) in `getFinalContext` you have all these if statements that add your predefined contexts to the global contexts and i think the error is here, as this globalcontexts list is never cleared and will never stop to grow over the time, and your last condition 
`if (!globalContexts.isEmpty()) {
            contexts.addAll(GlobalContextUtils.evalGlobalContexts(payload, globalContexts));
        }`

will add all the globalContexts to the event send.

Am i wrong? i hope :)

**Comment by djohannot** [comment]
i will test this fix and let you know if it resolve at least my issue:
https://github.com/djohannot/snowplow-android-tracker/tree/bugfix/duplicate-globalcontexts

**Comment by oguzhanunlu** [comment]
Ah! Right, sorry, I've forgot that we've switched the way we send predefined contexts in last release. They are sent as global contexts, since global contexts are tracker-level like predefined ones.

Alright, now we're on the same page that there is an issue with global contexts. Existing implementation doesn't handle duplication but before that, I'd not expect to see duplicate predefined contexts. It is probably due to multithreading issues.

I've checked your branch and it seems you use `tag` to identify global contexts in a map. We don't have a final decision on `tag`'s usage because we also considered `tag` as a way to group several contexts. Consider it as a namespace. However, solving duplication issue will probably be through using `tag` as you do.

I'm also working on improving test suite in the tracker these days but I'll make sure to update here as I have progress on this.

**Comment by oguzhanunlu** [comment]
Making `getFinalContext` `synchronized` will probably solve this issue.

**Comment by djohannot** [comment]
I doubt it will work, as the predefined context will still be added indefinitely to the global contexts.

You were right for the tag, it's not the right approach as there is no real context objects, they are SelfDescribingJson file, so i am doing a new test with the TrackerConstants as key of my global context maps. 

I have modify the test classes and it seems to work well, now i will do a real test. Also i have some issue running the tests as it only execute one class at a time and get stuck after :) don't know why.

Anyway i will keep you posted

**Comment by djohannot** [comment]
The fix i did seems to work really well!

Do you want to have a look at it? you can find the branch at the fork link i sent you previously

**Comment by oguzhanunlu** [comment]
@SzotsLevente @djohannot  Sorry for the delay here, I wasn't able to dig into the issue due to other priorities.

I think the problem is as following. The contexts that are natively supported (session, geolocation, mobile, screen etc.) are added by [calling](https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/Tracker.java#L617) `addGlobalContext` , which adds an instance of these contexts for each event to the list of global contexts, where successive events will also have previous events' contexts attached too, since all global contexts are evaluated for each event.

The solution is to add these natively supported contexts as they were before `1.2.0`, or move the chain of if statements somewhere else, where they won't get executed for each event.

It is a clear, simple yet very important implementation mistake in latest release where we wanted to leverage global contexts. I reverted the usage to the old way and first tests seem to fix the issue.

Our recent effort in improving trackers' test suite will hopefully prevent similar inconveniences in the future.

We're sorry for any inconvenience this has caused. Thanks for the understanding.
