### ISSUE TITLE
Not respect order when tracking fast in some cases

### ISSUE THREAD

**Issue by JoseFelixCastillo** [snowplow/snowplow-android-tracker#326]
I am trying to tracking in order some events, but if i track them fast (for example, pressing switch on and then pressing switch off), in some cases, not respect the order that i tracked. 
So Snowplow sending a buffer length for 8 request (for example) and some events are disorder, so i get 2 events successive with on value, and 2 events successive with off value.

Could it be that it was for the Executor class that you have in the code?

**Comment by jbeemster** [comment]
Hey @JoseFelixCastillo event order for emission and processing is not guaranteed anywhere in the snowplow pipeline - however each event should be tracked with an event created timestamp which allows you to query these events in the correct order _downstream_.  This is the "dtm" parameter.

Would you mind sharing what the use-case for having exact event order for transmission is?

**Comment by JoseFelixCastillo** [comment]
Well i see that we have a dvce_created_tstamp that i think is the timestamp when i created the event, rigth?

**Comment by jbeemster** [comment]
Hi @JoseFelixCastillo thats right - it is "dtm" in the outbound event from the Tracker which becomes "dvce_created_tstamp" in the data-warehouse after enrichment and loading.

**Comment by JoseFelixCastillo** [comment]
Ok @jbeemster thanks!
