### ISSUE TITLE
Support Multiple tracker instances

### ISSUE THREAD

**Issue by Khamisov** [snowplow/snowplow-android-tracker#332]
We have a use-case that we need to have 2 different instances of the tracker in the app 
With different NameSpace and APP_ID, Is there a possibility to support multiple trackers instead of having a Singleton? 

I think the IOS SDK supports multiple tracker instances too!

**Comment by AlexBenny** [comment]
I'm sorry for the very late reply.
The upcoming version 2.0 of the tracker will introduce the ability to instance multiple trackers.
I'm closing this issue as it's a duplicate of #426
