### ISSUE TITLE
Bump min Android API to 16+ 

### ISSUE THREAD

**Issue by AlexBenny** [snowplow/snowplow-android-tracker#349]
We currently support API 14+ corresponding at Android 4.0 Ice Cream Sandwich.
We want to move to API 16+ corresponding at Android 4.1 Jelly Bean.

**Comment by paulboocock** [comment]
What is the reason for the minimum version bump?

**Comment by AlexBenny** [comment]
Android 4.0 ICS is quite old and very few Android devices are still using API levels under 16.
Google Firebase dismissed support for older version too.
It would let us to make use of androidx libraries with less restrictions.
Something to think about for the next major release.
