### ISSUE TITLE
Cannot unset user id from subject

### ISSUE THREAD

**Issue by morganlutz** [snowplow/snowplow-android-tracker#353]
I'm currently setting the user id on a subject to `null` when the user logs out, however, instead of removing that value from the map, it sends `uid=null`. What is the recommended way to clear the `uid` from the subject map of values? 

```
Tracker.instance().subject.setUserId(user?.id)
```

**Comment by AlexBenny** [comment]
Hi @morganlutz , thanks for reaching us with this question. 
As you noticed this is a defect of the tracker as the `uid` field is not a required field and the Obj-C tracker removes the parameter when it's set to `null`.
I'll take care to correct it in the next Android tracker version.
