### ISSUE TITLE
Client session tracking does not work

### ISSUE THREAD

**Issue by morganlutz** [snowplow/snowplow-android-tracker#362]
Hi @AlexBenny 👋 

The android SDK uses this schema to track **client session** values:
[iglu:com.snowplowanalytics.snowplow/client_session/jsonschema/1-0-1](https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/client_session/jsonschema/1-0-1)

https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/constants/TrackerConstants.java#L34

However, currently the JSONSchema parsers fail when type arrays contain a single value with this error:
> Union Type Schemas must contain two or more Simple Type Schemas

We have opened a PR to fix this issue: https://github.com/snowplow/iglu-central/pull/1030 but are unsure how to push it through.

Are there any alternatives for us? Is there another way we can provide a different schema for session tracking other than forking this repo?

Thanks!

**Comment by paulboocock** [comment]
Hi @morganlutz 
We're going to have to update the client_session to 1.0.2 to fix this issue which will also involve an update to the android and objc trackers too.

I'll get things moving on our side now and keep you up to date! I'm optimistic it shouldn't take too long though.

**Comment by paulboocock** [comment]
How is this issue presenting itself to you @morganlutz? I see the validation issues in the schema that you describe but when I test client_session as an event context from an Android application, the data successfully ends up loading into my Data Warehouse - do you have a scenario where this is failing?

**Comment by morganlutz** [comment]
Hi @paulboocock 👋  My coworker wrote a more in depth explanation on the snowplow PR -
https://github.com/snowplow/iglu-central/pull/1030#issuecomment-596688258

**Comment by paulboocock** [comment]
Closing this as we can do an in-place mutation of the mentioned schema with the next iglu central release.
There is nothing to do in the Android SDK.
To clarify for other readers, `client_session` works fine for Snowplow loading, this is just a schema issue due to strict validation when using Fivetran.
