### ISSUE TITLE
ScreenView do not include previous screen state

### ISSUE THREAD

**Issue by hakanbagci** [snowplow/snowplow-android-tracker#363]
We are enabling screen context in our tracker so that we receive automatic screen view events. Until `1.3.5` release we were receiving previous screen parameters along with current screen parameters. After `1.3.5`, we realized that screen view events started not including previous screen related properties such as `previousName`. When I have checked the changes in this release I have seen that there was a change to fix #350 . It seems that the fix has broken previous state. 

I think following change in `ActivityLifecyclerHandler` is introduced the problem.

https://github.com/snowplow/snowplow-android-tracker/pull/351/commits/a2b59ba81d310660af3cb616d64769486a6d17a9#diff-a68e6e101e55b0c44f1fd0a1bdd4d615L64

Here `buildWithActivity` method do not fill any previous screen values which are available in tracker's current screen state. 

As a result, auto screen view tracking does not send any previous screen parameters after `1.3.5` release.

**Comment by AlexBenny** [comment]
Thanks for reporting this.  We'll look at it and get back soon.
