### ISSUE TITLE
Make session uuid rotation dependant on events being tracked

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/snowplow-android-tracker#366]
Some local tests have uncovered slightly unexpected behaviour of the session id incrementation logic. 

While testing the foreground and background timeouts (by setting them to 10s for example), some events came through with a new session id, but previous session id was not attributable to any previous session (see screenshot, timestamp is dvce_created).

I suspect that what's happening here is the foreground and background timeout settings come with a logic of:

"Whenever the timeout expires, rotate uuids"

However in my tests, the timeout expired twice without an event being sent, so the session id in the middle was 'lost'.

If this is the case, we can avoid it by only rotating the uuid at the point of creating an event - so every new session id is attached to an event.

In practice it's fairly unlikely that any reasonable usage for the timeouts would run into this issue.

![image](https://user-images.githubusercontent.com/25744626/78806221-4c58fe00-79ba-11ea-89e5-1ebb79827dc9.png)

**Comment by AlexBenny** [comment]
Some details about the implementation in the same issue on the iOS tracker repo: https://github.com/snowplow/snowplow-objc-tracker/issues/497#issuecomment-694858945
