### ISSUE TITLE
PushNotification Event described in docs but no class

### ISSUE THREAD

**Issue by schafdog** [snowplow/snowplow-android-tracker#370]
I  cannot find any classes to this. Has it been removed from code and not from documentation? 
Or not implemented yet?

There actual seem to be more differences between https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/android-tracker/android-1-4-0/  and implementation.

**Comment by AlexBenny** [comment]
Thanks for the heads up.
It's an error in the documentation. The Push Notification event has been implemented for iOS but not for Android yet. It has been probably added in the Android documentation for mistake.
I'll take care to fix the issue.
