### ISSUE TITLE
Question: Which Android SDK is supported by which tracker version

### ISSUE THREAD

**Issue by schafdog** [snowplow/snowplow-android-tracker#371]
Not an expert in android development. 

Does the latest version of this tracker support any version of Android SDK or is there a minimum?

If there is, can you point me to where to find that information?

**Comment by AlexBenny** [comment]
Hi @schafdog ,
thanks for raising this question.

The minimum Android SDK supported is the version 14.
It should correspond to the Android 4.0.2.

We are updating our [documentation](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/android-tracker/) and we will add soon that missing information.
Meanwhile, you can also find this information in the [gradle script](https://github.com/snowplow/snowplow-android-tracker/blob/1ec104a50aa29d56c7a1e8d619bb310abdca8e65/snowplow-tracker/build.gradle#L28) of the library.

**Comment by jolotan416** [comment]
Hi @AlexBenny, I tried using Snowplow Tracker 1.4.1 and it causes the following error for devices with Android API level below 21:

`java.lang.IllegalStateException: Expected Android API level 21+ but was 19
       at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
       at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
       at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
       at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:202)
       ...`

It seems the dependency OkHttp 3.14.16, which requires Android API level 21+ (https://square.github.io/okhttp/#requirements), is causing this problem.

Can you verify this and, if ever, be reflected in the documentation?

Thank you so much :)

**Comment by AlexBenny** [comment]
I've created a different issue about the OkHttp version and the minimum supported Android version.
The [documentation](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/android-tracker/android-1-4-0/) has been updated with the current min supported version (I've written API 21+ for now). I'll update it there as soon as the OkHttp version is correctly set.
