### ISSUE TITLE
Harden Install events where possible 

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/snowplow-android-tracker#384]
The latest version [patches an issue where install events lead to crashes](https://github.com/snowplow/snowplow-android-tracker/issues/377).

While install events won't cause crashes anymore here, I believe we would still fail to send installs when we run into the underlying issue.

I wonder if we could do something to change this - initial thoughts are that if the problem is the builder method, we might explore one of two (and a half) options: 

a) return a promise somewhere to ensure that the builder method exists when called
or
b1) when we currently call install event, instead of attempting to send the event, we store the JSON/SDJSon for it, and build it later
or
b2) we call install event as we do now, but when it fails we store the data somewhere and re-attempt building later 

Not sure if any of these options are viable.

**Comment by AlexBenny** [comment]
Closing as part of the wide refactoring of the upcoming version 2.0.
See #426
