### ISSUE TITLE
Doc update: make clear what happens when user ticks "Opt out of Ads Personalisation

### ISSUE THREAD

**Issue by shermozle** [snowplow/snowplow-android-tracker#399]
This code block:
https://github.com/snowplow/snowplow-android-tracker/blob/0ab5eeaf15eea7ca9562cf96dd28a034b97c668c/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/utils/Util.java#L431
seems to indicate that if the user ticks the option "Opt out of Ads Personalisation", the tracker sends a _blank string_ for the `android_idfa`. If the ads library isn't loaded it sends `NULL`.

Would be good to mention this in [the documentation](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/android-tracker/android-1-4-0/#aaid-tracking).

(I just wasted more of @mocovenwitch's time than I'd like hunting this down)

**Comment by AlexBenny** [comment]
Thanks for reporting this.
We are going to update the documentation in order to clear out this important detail.

**Comment by AlexBenny** [comment]
Doc corrected here: https://spdocsstaging.wpengine.com/docs/collecting-data/collecting-from-own-applications/android-tracker/android-1-5-0/#aaid-tracking
