### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by colinrtwhite** [snowplow/snowplow-android-tracker#411]
The Snowplow Android SDK uses the Android Support library [which is unmaintained and hasn't been updated in ~2 years](https://developer.android.com/topic/libraries/support-library/revisions). The SDK should migrate to AndroidX to get the latest bug fixes and updates. Moreover, using the SDK currently requires using Jetifier which [slows down build speed by up to ~40%](https://adambennett.dev/2020/08/disabling-jetifier/). We're in the process of attempting to remove Jetifier to speed up our builds, however Snowplow is our last dependency that hasn't updated.

**Comment by AlexBenny** [comment]
Hi Colin, thanks for the heads up,
the migration to AndroidX is planned for the version 2.0 of the Snowplow Tracker. It should be ready in the next few months.
We attempted the migration to AndroidX recently but, unfortunately, we needed to revert to Android Support library in order to avoid breaking changes.

**Comment by colinrtwhite** [comment]
@AlexBenny Is there an update on the timeline for the 2.0 release? At Instacart this is still our last dependency that hasn't updated and it's blocking us from removing Jetifier.

**Comment by AlexBenny** [comment]
Hi @colinrtwhite , we already started to work on the version 2.0 and we plan to release a first Android beta version in early February.
For reference, here the RFC doc about v.2.0: https://discourse.snowplowanalytics.com/t/rfc-mobile-trackers-v2-0

**Comment by colinrtwhite** [comment]
@AlexBenny Is the first 2.0 beta available? You mentioned it would be released in early February.

**Comment by AlexBenny** [comment]
Hi @colinrtwhite , unfortunately it's not ready yet. We had some delays. We aim to release a beta version for both trackers in a few days. Indicatively the 3rd week of March.

**Comment by colinrtwhite** [comment]
@AlexBenny Sorry to keep pinging you on this, any update on the 2.0 release?

**Comment by AlexBenny** [comment]
@colinrtwhite Really sorry for this delay. We had some blockers last week that stopped the release. I plan to start the release process of the beta version Tuesday. So, indicatively next Tuesday or Wednesday it should be released.
I'll keep you informed as soon as it's ready!

**Comment by paulboocock** [comment]
Hey @colinrtwhite 
We found an issue with session tracking in v2, across iOS and Android, that we needed to resolve that pushed this release back a little.

To give you as much information as to where we are at with v2 of our mobile trackers, we next need to push a small release of the iOS tracker (to solve an IDFA issue) then we will be straight into releasing the betas of the Android and iOS v2 trackers which will include this change. That will likely be next week. 

So it's close but there is still a little wait. 

Barring anything major being discovered during the beta release, we anticipate being able to get the final v2 into your hands in April.

**Comment by AlexBenny** [comment]
Hi @colinrtwhite , sorry for the long waiting. We just released the version 2.0.0-beta.1 which supports AndroidX.
Some more details and the link to the migration guide are here: https://discourse.snowplowanalytics.com/t/snowplow-android-tracker-2-0-0-beta-1-release/5004

The final official release will be later this month. Any feedback is really appreciated!
The iOS beta version will be released early next week.

**Comment by colinrtwhite** [comment]
Awesome, thank you!
