### ISSUE TITLE
Cannot provide OkHttp client when setting up Emitter

### ISSUE THREAD

**Issue by nyounis2** [snowplow/snowplow-android-tracker#414]
Emitter allows you to provide your own OkHttpClient [here](https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/Emitter.java#L252) . However when you take a look at the OkhttpNetworkConnection class responsible for making the http request, it does not seem to be using that client. the constructor of that class instantiates its own OkhttpClient instead of using the one associated with the parameter passed (builder.client) in [here](https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/OkHttpNetworkConnection.java#L164).as a result I'm unable to pass any headers to attach to the http request made

**Comment by AlexBenny** [comment]
Thanks @nyounis2 for the heads up.
We are going to fix the bug you reported in the patch version 1.7.1
