### ISSUE TITLE
ScreenView ID preconditions breaking change

### ISSUE THREAD

**Issue by QuirijnGB** [snowplow/snowplow-android-tracker#416]
**Describe the bug**
The SDK seems to have changed its behaviour without documenting it as a breaking change. Or the documentation is out of date.

Since release [1.3.5](https://github.com/snowplow/snowplow-android-tracker/releases/tag/1.3.5) the ScreenView id *has* to be a UUID which was not the case, and in the [docs](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/android-tracker/android-1-7-0/) it just uses `some string`.

**Expected behavior**
Clear documentation what this is used for

**Comment by AlexBenny** [comment]
Hi @QuirijnGB , thanks for reporting this and sorry for the delay.

As you pointed out the documentation is not correctly updated. We are going to fix it as soon as possible.
About the ScreenView id, I've just replied to another issue on the same topic.

I add here the link to the other issue for more details about why the version 1.3.5 enforces to use UUID string for the ScreenView ID: https://github.com/snowplow/snowplow-android-tracker/issues/418
