### ISSUE TITLE
Fix OkHttpClient sslSocketFactory always overriden

### ISSUE THREAD

**Issue by hakanbagci** [snowplow/snowplow-android-tracker#417]
`Emitter.Builder` allows passing a custom `OkHttpClient` while building an `Emitter`. However, that client's `sslSocketFactory` is always being overriden [here](https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/OkHttpNetworkConnection.java#L167).

This prevents enabling certificate pinning or adding some custom certificates to `OkHttpClient` instances. I think Snowplow SDK should not override anything in user provided `OkHttpClient` instance to not break user's OkHttp configuration. 

Is it possible to modify that part so that it looks like something similar to following?

```java
        if (builder.client == null) {
            client = new OkHttpClient.Builder()
                    .sslSocketFactory(tlsArguments.getSslSocketFactory(), tlsArguments.getTrustManager())
                    .connectTimeout(15, TimeUnit.SECONDS)
                    .readTimeout(15, TimeUnit.SECONDS)
                    .build();
        } else {
            client = builder.client;
        }
```

**Comment by AlexBenny** [comment]
Hi @hakanbagci , thanks for reporting this.

> I think Snowplow SDK should not override anything in user provided OkHttpClient instance to not break user's OkHttp configuration.

I agree with you, we will update it as you suggested in the next version!
