### ISSUE TITLE
Migrate releases to Maven Central

### ISSUE THREAD

**Issue by BobString** [snowplow/snowplow-android-tracker#424]
JCenter is shutting down in 12 months
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Please transfer the snowplow tracker from jcenter to any other hosting service

**Comment by paulboocock** [comment]
Thanks. This is on our radar. We intend to have a solution in place for our next major release (which isn't too far away now 🎉). It's extremely likely we will be publishing to Maven Central.

**Comment by paulboocock** [comment]
We've now moved all existing releases that were on Bintray/JCenter to Maven Central (0.6.0 to 1.7.1).

https://search.maven.org/artifact/com.snowplowanalytics/snowplow-android-tracker/1.7.1/aar

**Comment by BobString** [comment]
Awesome thanks!!
