### ISSUE TITLE
Add SubjectController to update userId

### ISSUE THREAD

**Issue by rlatapy-luna** [snowplow/snowplow-android-tracker#447]
**Is your feature request related to a problem? Please describe.**
Before version 2.0.0, I was updating the subject userId using `Tracker.instance().subject.setUserId(user?.id)` from an user observer. I'm actually migrating to the 2.0.0, but I cannot find a similar way to update the userId dynamically.

**Describe the solution you'd like**
A light way to update the `SubjectConfiguration.userId` on the fly

**Describe alternatives you've considered**
Recreate the tracker with an up-to-date `SubjectConfiguration` (How can I get the current user id so I can check if it changes before recreating the tracker?)

**Comment by AlexBenny** [comment]
Thanks for reporting this @rlatapy-luna ,
You raised an important problem of configurability we initially planned a small refactoring of the identifiers but it slipped away from this first release.
I put this fix among the high priority tasks.
