### ISSUE TITLE
Allow enabling/disabling IDFA

### ISSUE THREAD

**Issue by Ehab4290** [snowplow/snowplow-android-tracker#450]
Sending IDFA may not be GDPR compliant, so it would be great to allow enabling/disabling apart from enabling/disabling the mobile context. Specially, it is not a required field in mobile context schema.

**Comment by AlexBenny** [comment]
Thanks for reporting this. 
For completeness, the IDFA will not be tracked automatically if the Google Mobile Ads library is not added as dependency of the app. If it isn’t included, the tracker will not send the IDFA with the events.
However, your suggestion is definitely an important enhancement that we will consider in the upcoming versions.

**Comment by matus-tomlein** [comment]
Will be addressed in #598
