### ISSUE TITLE
Fix trueTimestamp not set by SelfDescribing builder

### ISSUE THREAD

**Issue by colinrtwhite** [snowplow/snowplow-android-tracker#451]
**Describe the bug**
The `trueTimestamp` builder method for `SelfDescribing` does not set the `trueTimestamp` value for the built event.

**To Reproduce**
Here's a test case to reproduce the issue:

```kotlin
val date = Date()
val event = SelfDescribing.builder().trueTimestamp(date).build()
assertEquals(date, event.trueTimestamp)
```

Currently that case will fail as `event.trueTimestamp` is null.

**Expected behavior**
`SelfDescribing.builder().trueTimestamp` should set the `trueTimestamp` for the built event.

**Additional context**
This can be worked around by setting `SelfDescribing.trueTimestamp` since it is a public property:

```kotlin
val date = Date()
val event = SelfDescribing.builder().build()
event.trueTimestamp = date
```

I'm using version `2.0.1` of the library.

**Comment by paulboocock** [comment]
Thanks for the bug report. We will resolve this in the upcoming release.
