### ISSUE TITLE
Fix Gdpr context being tracked without enabling it

### ISSUE THREAD

**Issue by plastiv** [snowplow/snowplow-android-tracker#457]
**Describe the bug**
Gdpr context is auto tracked even though I haven't configured it

```json
    {
      "schema": "iglu:com.snowplowanalytics.snowplow\/gdpr\/jsonschema\/1-0-0",
      "data": {
        "documentDescription": null,
        "basisForProcessing": "contract",
        "documentId": null,
        "documentVersion": null
      }
    },
```

**To Reproduce**
I'm migrating the existing codebase from 1.7.1 to 2.1.0 I assume it's how Gdpr controller is initialized by default. But if it's actually unexpected to see these Gdpr contexts then I can try to narrow it down in scope and create a minimal viable example.

**Expected behavior**
There is a way to disable Gdpr context as other contexts (platform, session, application, etc.)

**Additional context**
Is it safe/correct for now to disable Gdpr auto context with

```kotlin
  return Snowplow.createTracker(
            context,
            NAMESPACE,
            networkConfiguration,
            trackerConfiguration,
            sessionConfiguration,
            emitterConfiguration,
            subjectConfiguration,
            globalContextsConfiguration
        ).apply {
            gdpr.disable() 
        }
```

**Comment by paulboocock** [comment]
Hey @plastiv 

Thanks for the bug report. This looks like it was introduced in v2.1.0, we'll get it fixed soon.

Disabling the GDPR context after intiialisation is the correct workaround until we get this fixed.

**Comment by paulboocock** [comment]
I think this line is where the issue occurs: https://github.com/snowplow/snowplow-android-tracker/blob/eb0d6592ab62cf8b23c972e9afdb23f9637daac1/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/internal/tracker/ServiceProvider.java#L397

The `GdprConfigurationUpdate` is never `null` so we always end up included it when creating the tracker, we should probably be checking the sourceConfig property instead.
