### ISSUE TITLE
TLS certificate expired

### ISSUE THREAD

**Issue by krobert** [snowplow/snowplow-android-tracker#486]
Hey,

Currently im unable to compile any project that is using snowplow:
```
Could not determine the dependencies of task ':platform-mobile:compileProductDebugKotlin'.
> Could not resolve all files for configuration ':platform-mobile:productDebugRuntimeClasspath'.
   > Could not resolve com.snowplowanalytics:snowplow-android-tracker:2.+.
     Required by:
         project :platform-mobile > project :library-analytics
      > Failed to list versions for com.snowplowanalytics:snowplow-android-tracker.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/snowplowanalytics/snowplow-android-tracker/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/snowplowanalytics/snowplow-android-tracker/maven-metadata.xml'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.2/userguide/build_environment.html#gradle_system_properties
                  > PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

This is the issue, using the latest 2.2.1 with aar, is there an artifactory published somewhere?
Its not in the readme anywhere and i cant find it on google.
Its blocking my dailiy work, are you aware of this issue?

**Comment by AlexBenny** [comment]
Thanks @krobert for raising this issue.

JCenter is shutting down, probably the reason is that.
We moved all existing releases that were on Bintray/JCenter to Maven Central. 
https://search.maven.org/artifact/com.snowplowanalytics/snowplow-android-tracker/2.2.1/aar

I'll take a note to improve the documentation and state it clearly.
I'm closing the issue as I suspect that is the source of the problem.
Please, reopen it in case it persist!

**Comment by krobert** [comment]
@AlexBenny i can confirm its working without aar, please update the docs:
https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/mobile-trackers/mobile-trackers-v2-0/quick-start-guide/#tab-android-tracker
