### ISSUE TITLE
Advertising ID retrieval creates new thread

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#50]
> Advertising ID is obtained by creating a new thread, which is considered very bad practice.

Raised by @hamidp

**Comment by jbeemster** [comment]
The advertising id fetch has been changed based on trello/snowmans implementation:
https://github.com/trello/snowman/blob/master/library/src/main/java/com/trello/snowman/SnowmanUtil.java#L65-L80

Our implementation:
https://github.com/snowplow/snowplow-android-tracker/blob/develop/snowplow-android-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/Subject.java#L187-L196
