### ISSUE TITLE
Calculate screen_view duration

### ISSUE THREAD

**Issue by justramgerry** [snowplow/snowplow-android-tracker#503]
**Is your feature request related to a problem? Please describe.**
Have you considered adding screen or session  pings to allow calculate user timespent on certain pages / during whole session?

**Describe the solution you'd like**
Some solution similar to existing in JS tracker – sending standard event each 5/10 seconds

**Comment by AlexBenny** [comment]
Reference to same issue on iOS: https://github.com/snowplow/snowplow-objc-tracker/issues/670

**Comment by matus-tomlein** [comment]
This has been implemented in #654 and released in version 6.0.0!
