### ISSUE TITLE
Emitter.addToBuffer can lead to network on UI thread if set to immediately flush

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#52]
Raised by @hamidp

**Comment by jbeemster** [comment]
All network communications have been reimplemented within RxJava and a background Scheduler.  
Relevant Issue: https://github.com/snowplow/snowplow-android-tracker/issues/49

As such this is no longer an issue.

**Comment by jbeemster** [comment]
Closing this has been done/
