### ISSUE TITLE
Deep link context & Deep link received event send referrer as "null" string if it is absent

### ISSUE THREAD

**Issue by Ehab4290** [snowplow/snowplow-android-tracker#522]
**Describe the bug**
Both deep link schema (https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.mobile/deep_link/jsonschema/1-0-0) and deep link received schema (https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.mobile/deep_link_received/jsonschema/1-0-0) define `referrer` as optional and its format is `uri`. SDK sends it as `"null"` string if it's absent and enricher is validating them using their schemas. So the validation for this field fails as it is expected to have `uri` format.

**To Reproduce**
Track `DeeplinkReceived` event without providing `referrar`.

**Expected behavior**
I would expect If `referrer` is null then it is not added to JSON as it is already optional

**Device informatoin (please complete the following information):**
 - Device: all devices
 - OS: all Android version
 - Version 3.1.2

**Comment by AlexBenny** [comment]
Hi @Ehab4290 , thanks for reporting this issue.
I've done a quick check and from the tests and the code it seems that the tracker [should strip out the null values](https://github.com/snowplow/snowplow-android-tracker/blob/3a93694e468daa652da7ac5bd4bbbd43f9eef9a2/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/event/DeepLinkReceived.java#L112-L113) from DeepLinkReceived and DeepLink.
I suspect that the "null" string is assigned to referrer somewhere else.
Do you create the DeepLinkReceived event with `DeepLinkReceived fromIntent(@Nullable Intent intent)` or `fromReferrerDetails(@Nullable ReferrerDetails referrerDetails` ?

**Comment by Ehab4290** [comment]
Hi @AlexBenny, 
I've realized that "null" was assigned from my implementation. 
Thanks for your efforts and sorry for the confusion
