### ISSUE TITLE
Emitter.addToBuffer does a sync write to database

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#53]

**Comment by jbeemster** [comment]
The EventStore now adds all events to the database using an RxJava Observable function.  This function no longer blocks on any thread.

Relevant Code: https://github.com/snowplow/snowplow-android-tracker/blob/develop/snowplow-android-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/storage/EventStore.java#L89-L140

**Comment by jbeemster** [comment]
Closing as this has been fixed wit RxJava.
