### ISSUE TITLE
Ensure english numerals are used in datetimes

### ISSUE THREAD

**Issue by matus-tomlein** [snowplow/snowplow-android-tracker#537]
When setting the `firstEventTimestamp` in the client session entity, we make use of `SimpleDateFormatter` which results in localized date formats (e.g., in Arabic). Instead of it, we should make use of the `java.time` APIs as [recommended here](https://stackoverflow.com/questions/67141299/simpledateformat-date-comes-in-arabic).

**Comment by mscwilson** [comment]
Unfortunately the [DateTimeFormatter](https://developer.android.com/reference/java/time/format/DateTimeFormatter) was added to Android API level 26, but we are supporting API 21.

**Comment by matus-tomlein** [comment]
Interesting, then I think we'll have to do with the `SimpleDateFormatter` but we should fix the Arabic localization of the dates by setting an explicit locale, such as:

```java
SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", new Locale("en"));
```
