### ISSUE TITLE
Call AsyncTask.get in sendGetData and setPostData will block UI thread

### ISSUE THREAD

**Issue by czchen** [snowplow/snowplow-android-tracker#54]
In `sendGetData` and `setPostData` in `Emitter` [0], they call `AsyncTask.get` to get HTTP response. `sendGetData` and `setPostData` in `Emitter` are called in UI thread since they use `AsyncTasks`. However, they also use  `AsyncTask.get` [1] to get HTTP response, which will block the UI thread if HTTP response is not returned. It might slow down UI thread and cause bad UI experience.

[0] https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-android-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/android/emitter/Emitter.java#L181-L217
[1] https://developer.android.com/reference/android/os/AsyncTask.html#get()

**Comment by alexanderdean** [comment]
Hi @czchen - you are right. Sorry about this. See also: #50 

We are planning a reboot of the Android Tracker shortly, to hopefully fix these issues and generally improve the API, hopefully based on code developed by @hamidp . I will keep you posted.

**Comment by czchen** [comment]
Hi @alexanderdean 

Is it possible to release a minor version just to remove these two `AsyncTask.get` so that UI thread will not be blocked?

**Comment by alexanderdean** [comment]
If you make the PR, I can certainly get that released...

**Comment by czchen** [comment]
The `com.snowplowanalytics.snowplow.tracker.core.emitter.Emitter` has the same problem. The `future.get()` will block the current thread. The `requestMethod` becomes meaningless because both `RequestMethod.Synchronous` and `RequestMethod.Asynchronous` block the current thread.

https://github.com/snowplow/snowplow-java-tracker/blob/master/snowplow-java-tracker-core/src/main/java/com/snowplowanalytics/snowplow/tracker/core/emitter/Emitter.java#L210-L212

**Comment by alexanderdean** [comment]
@jonalmeida - comments on this?

**Comment by hamidp** [comment]
I looked at this a bit and it's turtles all the way down since the components are tightly coupled. The only way to fix from what I can tell is to make sure to call track from not a main thread.

**Comment by alexanderdean** [comment]
Thanks @hamidp. My preference is to get the full reboot started rather than plastering over bits and bobs. I'll reply to your email shortly...

**Comment by jonalmeida** [comment]
Would it be easier then to create a small patch calling track from a separate thread until the rewrite, or to call `AsyncTask.get(long timeout, TimeUnit unit)`?

**Comment by hamidp** [comment]
FYI, the tracker I've been writing for Trello's purposes is here: https://github.com/trello/trelloplow

It's not ready yet for consumption yet, but I hope that within a week or two it should be usable.

**Comment by alexanderdean** [comment]
This has been resolved in 0.3.0 and 0.4.0, closing
