### ISSUE TITLE
Add anonymous tracking features

### ISSUE THREAD

**Issue by matus-tomlein** [snowplow/snowplow-android-tracker#540]
Anonymous tracking is a feature currently implemented in the JavaScript tracker that enables anonymising various user and session identifiers. It affects the following user and session identifiers:

1. Client-side user identifiers: `domain_userid` (equivalent to `client_session.userId` in session context). On mobile, there are also the IDFA identifiers in the `mobile_context` platform context entity.
2. Client-side session identifiers: `domain_sessionid` (equivalent to `client_session.sessionId` in session context)
3. Server-side user identifiers: `network_userid` and `user_ipaddress`

There are several levels to the anonymisation depending on which of the three categories are affected:

## 1. Full client-side anonymisation

In this case, both the client-side user identifiers as well as the client-side session identifiers are anonymised.

### Current options in mobile trackers

One could disable tracking both the `client_session` and `mobile_context` context entities:

```
trackerConfig.sessionContext = false
trackerConfig.platformContext = false
```

### TODO in mobile trackers

Disabling the platform context altogether may be a bit wasteful as there is other information (e.g., memory usage, carrier, OS) that are not user or session identifiers (although they could be used for fingerprinting). We could provide an option to only disable the IDFA identifiers in the platform context:

```
trackerConfig.userAnonymisation = true
```

This could set them to null (they are not required in the platform context schema).

## 2. Client-side anonymisation with session tracking

In this case, client-side user identifiers should be disabled but session identifiers should still be tracked.

### Current options in mobile trackers

This is currently not possible in the mobile trackers.

### TODO in mobile trackers

We could provide an option to enable session context while disabling all user identifiers (both the ones in `client_session` and `mobile_context` context entities):

```
trackerConfig.sessionContext = true
trackerConfig.userAnonymisation = true
```

The `userId` in `client_session` is a required property, so this could always set it to `00000000-0000-0000-0000-000000000000`.

## 3. Server-side anonymisation

This disables setting the server-side cookies with `network_userid` and also anonymizes the user IP address.

### Current options in mobile trackers

This is currently not possible in the mobile trackers.

### TODO in mobile trackers

We could add an option to the tracker configuration:

```
trackerConfig.serverAnonymisation = true
```

This would set the `SP-Anonymous: *` HTTP header for requests going to the Collector. The collector will take care of not setting the request headers and anonymizing the IP address.

**Comment by AlexBenny** [comment]
Thanks, this is a great starting point. I don't have any particular feedback and from the API point of view I think it's good to have something similar to what is already present in the web tracker.

About the `client_session.userid`, I wonder what's the impact for the data modeling. IMO the best would be to create a userId that is reset every time the session expire. Probably in the web it's not a problem because the data modelling is based on other identifiers (e.g.: PageView id).

Tagging @emielver as he has worked in the mobile data model and maybe he can have opinions on this feature.
Also this can be good to progress towards the unification of the two models (mobile and web).

**Comment by matus-tomlein** [comment]
Apart from how to handle the anonymised `client_session.userId` property, one other interesting design issue comes up:

The server anonymisation setting results in a HTTP header being added to the request to collector. However, requests are constructed at a different time than when the payload is built. This means that an event may be tracked with server anonymisation enabled, then be added to the event queue, but the request to the collector can be executed much later (e.g., due to internet issues) when server anonymisation is already disabled. This could result in ignoring the server anonymisation.

There is a trade-off to be made whether we should store the server anonymisation setting along with the payload in the event queue or just use the anonymisation setting at the time when the requests are made. The JavaScript tracker went for the latter option and uses the server anonymisation setting at the time when requests are sent. Mobile might be a slightly different case as it is more likely that events will be sent later than tracked (more likely to be offline and different emitter behaviour with more event batching).

However, storing the server anonymisation setting along with payloads could complicate things quite a bit – change how the payloads are stored and also would require us to make separate requests in case the event queue contains both events tracked with and without server anonymisation (more complicated Emitter logic).

I think I'm more inclined to take the pragmatic approach and check the server anonymisation flag at the time requests are sent as done by the JavaScript tracker. Just wanted to document the trade-off here and open the discussion in case there are other opinions. The problem does not affect the user anonymisation setting (which is applied at the time the payloads are created).

**Comment by AlexBenny** [comment]
> we should store the server anonymisation setting along with the payload in the event queue or just use the anonymisation setting at the time when the requests are made.

Interesting point! The solution I like is the first one but I agree that it would require much more effort. If JS uses the second option it seems sensible to follow the same approach for the mobile trackers too.

Probably, we might implement the first option once we have some more cases/features where extra info need to be added to the event/payload during its journey inside the tracker.

**Comment by emielver** [comment]
Thanks for including me in this! So from a data modelling perspective nothing will break if users disable both the tracking of sessions and users, but the data models won't really work although that's a natural consequence of not enabling the tracking of session and users means we can't then build the sessions and users data models. Snowplow users can still track screen views and that will all work fine.

It does depend on how they disable tracking though. If the contexts are just completely empty then Snowflake/Databricks can handle them but BigQuery kicks up a fuss that you can't access the field inside a struct if it doesn't exist. So do you think you'd still pass along the context but just put the `sessionId` and `userId` fields to `NULL` or would you remove the context altogether?

**Comment by matus-tomlein** [comment]
Hi @emielver, thanks!

I think the main case that we are unsure about is the second one where we still want to track sessions (add the session context entity to events) but remove the `userId` identifier from it. We can't set it to `NULL` because it is a required property of the schema. So I was thinking of setting it to an all-zero UUID (`00000000-0000-0000-0000-000000000000`) – I think that is how the `network_userid` behaves if server anonymization is enabled.

Other options would be to set it to the same value as the `sessionId`. This would make them change at the same time. Or we could just generate a random `userId` every time.

What do you think is the best here?

**Comment by emielver** [comment]
I think either option works from a data modelling perspective. If you were to set it to an all-zero UUID then it just means that the `user` data model would be nonsensical since it would aggregate all activity to the user, but if you were to set it to the same value as `sessionId` then it would just be modelled in exactly the same manner as the `sessions` data model. In any case I'm not sure it matters too much because if you have disabled user tracking then you should also disable user data modelling.

I think in terms of consistency we should then stick with the all-zero UUID!
