### ISSUE TITLE
Track the App set ID (Android IDFV) in platform context

### ISSUE THREAD

**Issue by mscwilson** [snowplow/snowplow-android-tracker#565]
In the [Snowplow iOS tracker](https://github.com/snowplow/snowplow-objc-tracker), the platform context automatically adds the Apple IDFA (ID for advertising) and IDFV (ID for vendor) identifiers, if they are configured. The Android tracker adds the Android equivalent of the IDFA, AAID, to the platform context entity (as `androidIdfa`).

The Android `App set ID` is the equivalent "ID for vendor" identifier of the Apple IDFV. It would be good if it was also automatically added to the platform context.

**Comment by KCaimo** [comment]
Some news here?

**Comment by mscwilson** [comment]
Hi @KCaimo! This is in our roadmap for Q1. Sorry we can't be more specific on time frames. We are focussing on the v5 Kotlin translation right now.

**Comment by jellevdvliet** [comment]
Hi, I'm curious if this is implemented?

**Comment by mscwilson** [comment]
Hi @jellevdvliet, not yet! But we have started work on it. Will be implemented within Q1.

**Comment by KCaimo** [comment]
Will thix require a SDK upgrade in the android apps?

**Comment by matus-tomlein** [comment]
Unfortunately, this has been blocked by problems with publishing a new version of the platform context schema. We are working to resolve the issues but will most likely be able to publish the schema and work on this feature at the beginning of the next quarter.

**Comment by matus-tomlein** [comment]
I have some bad news regarding the timeline for getting this feature out. Although we are working on removing the blocker for publishing the required schema changes, it will be a bit more delayed than we previously expected as we plan to publish it together with some other changes.

Our current estimate is that we will have this feature out at the beginning of May.

For anyone wanting to track the app set ID earlier, it's possible to track it in a custom context entity for now. Either define a custom schema for the entity or add the property to an existing schemas. Fetching the ID is relatively straightforward and [is documented here](https://developer.android.com/training/articles/app-set-id). Finally, the fetched ID can be attached to all events using a global context configuration.

**Comment by mscwilson** [comment]
We are intending it to be a minor release.

**Comment by matus-tomlein** [comment]
The issue was addressed in #598 and released in 5.1.0 release of the tracker.
