### ISSUE TITLE
RxJava/Classic: update event sending tests to use okhttp mocks over mountebank

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#62]
A nice complement to Mountebank, plus they come with lots of helper libs to make the test asserts easier: 

* https://github.com/snowplow/snowplow-java-tracker/blob/master/src/test/java/com/snowplowanalytics/snowplow/tracker/EmitterTest.java
* https://github.com/snowplow/snowplow-java-tracker/blob/master/src/test/java/com/snowplowanalytics/snowplow/tracker/TrackerTest.java

**Comment by jbeemster** [comment]
Didn't get a chance to look into this, will re-schedule for 0.5.0.

**Comment by alexanderdean** [comment]
Following review, rename this ticket to implement some initial WireMock tests or similar...
