### ISSUE TITLE
Add user timings event

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#63]
Implementation similar to: https://developers.google.com/analytics/devguides/collection/android/v4/usertimings

**Comment by jbeemster** [comment]
@alexanderdean are we talking about a Tracker function which is essentially a wrapper for an unstructured event for this one?  A bit like trackScreenView I guess.

**Comment by alexanderdean** [comment]
Yep exactly that! The iOS tracker has it implemented already.
