### ISSUE TITLE
Missing migration steps for ecommerce events 5.4.0 release

### ISSUE THREAD

**Issue by plastiv** [snowplow/snowplow-android-tracker#631]
**Is your feature request related to a problem? Please describe.**

For teams that are currently using 

```
import com.snowplowanalytics.snowplow.event.EcommerceTransaction
import com.snowplowanalytics.snowplow.event.EcommerceTransactionItem
```

The migration path to the newly dropped `ecommerce` package is unclear. 

- Should DB be updated? 
- Does it depend on some server release? 
- Does it depend on server configuration? 
- Do we need to manually handle the data migration for existing applications?
- Is it a data-breaking format change or just a drop of kotlin data classes?

**Describe the solution you'd like**

Would like to know the motivation behind the release and some notes on how to handle the migration for existing apps tracking ecom events with previous versions of the snowplow sdk.

**Additional context**

We currently use android snowplow tracker v5.2.0

**Comment by mscwilson** [comment]
Hi plastiv, sorry we didn't get back to you until now. We'll be adding some documentation to answer your questions soon, I'll let you know when it's ready. Thanks for the suggestion.

**Comment by mscwilson** [comment]
The [migration guide](https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/migration-guides/migration-guide-to-new-ecommerce/) is out! Let us know if you still have questions.
