### ISSUE TITLE
Enabling R8 Full mode breaks the demo apps

### ISSUE THREAD

**Issue by Andr3Carvalh0** [snowplow/snowplow-android-tracker#652]
**Describe the bug**
When R8 full mode is on, the demo code breaks. This is important cause from gradle version 8.0+ R8 full mode is on by default

**To Reproduce**
Ive created a demo [here](https://github.com/Andr3Carvalh0/snowplow-android-tracker). All you need to do is build the `release` variant of the snowplow-demo-compose

**Expected behavior**
Whether R8 full mode is on or off tracking should work

**Screenshots**
When I compile the demo with the `android.enableR8.fullMode` set to `true`, I get this error
<img width="531" alt="Screenshot 2023-12-07 at 18 03 46" src="https://github.com/snowplow/snowplow-android-tracker/assets/6016433/b8c37974-a458-4c3c-848e-914ff08ceb83">

If I still minify the app, but disable R8 Full mode, the app works normally

**Device informatoin (please complete the following information):**
 - Device: Any
 - OS: Any
 - Version: Any
 
Only requirement is that you minify your code using R8 full mode

**Comment by matus-tomlein** [comment]
Thanks for reporting this @Andr3Carvalh0, we will look into it!

**Comment by eygraber** [comment]
Looks similar to an issue I've had in the past - https://issuetracker.google.com/issues/188703877
