### ISSUE TITLE
Android InstallReferrerDetails: install_begin_timestamp & referrer_click_timestamp always wrong and install_begin_timestamp often missing

### ISSUE THREAD

**Issue by davidher-mann** [snowplow/snowplow-android-tracker#687]
We came across that install_begin_timestamp and referrer_click_timestamp are always wrong, since the Snowplow SDK assumes that the Google Play installreferrer API response is in milliseconds but it is actually in seconds since epoch.

As you can see in this screenshot, I was able to proof this. I corrected the install_begin_timestamp through multiplying it by 1000 and got the correct timestamp. 
<img width="1182" alt="timestamp issue proof from BigQuery" src="https://github.com/snowplow/snowplow-android-tracker/assets/43452069/d4ce11ee-d557-4bdd-883b-19a1ad16f582">

**Source from the official API documentation regarding the response format**
- install_begin_timestamp: The timestamp, **in seconds**, of when a referrer click happened (both client- and server-side)
- referrer_click_timestamp: The timestamp, **in seconds**, of when an installation began (both client- and server-side)
https://developer.android.com/google/play/installreferrer

Related file:
https://github.com/snowplow/snowplow-android-tracker/blame/07536ea8db236e8f6efd74b07f3af901a136846e/snowplow-tracker/src/main/java/com/snowplowanalytics/core/tracker/InstallReferrerDetails.kt#L70-L71

Further more, the install_begin_timestamp is missing for about 30% of installs (sample size ~145k installs on Android 8 and higher).We are running InstallReferrer package to v2.2 and Snowplow Tracker versions 5+
<img width="691" alt="missing install_begin_timestamp" src="https://github.com/snowplow/snowplow-android-tracker/assets/43452069/fe42b821-6cf1-4b13-bd1f-47e9d4b8b204">

**Comment by mscwilson** [comment]
thanks for the report 😵

**Comment by mscwilson** [comment]
@davidher-mann is it just the `install_begin_timestamp` missing in those 30% of installs, or the `referrer_click_timestamp` as well? Do you know anything more about the events where it's missing, maybe about device?
