### ISSUE TITLE
Device (TANK2) send negative battery level

### ISSUE THREAD

**Issue by opengamer29** [snowplow/snowplow-android-tracker#698]
**Describe the bug**
It looks like a specific Android device (TANK 2 - Rugged Smartphone with Built-in Laser Projector) reports its battery level wrong. It leads to [scheme validation](https://github.com/snowplow/iglu-central/blob/4169dec5767e59b0be87ec35a54e70acbae178e7/schemas/com.snowplowanalytics.snowplow/mobile_context/jsonschema/1-0-3#L75) failure. That triggers a lot of pseudo errors and we may miss the important ones.

**To Reproduce**
- find a TANK 2 - Rugged Smartphone with Built-in Laser Projector device
- install any application with SDK on it
- enable enrichment
- send some events from the device

**Expected behavior**
It's a device-specific bug and [omitting negative battery level values inside SDK](https://github.com/snowplow/snowplow-android-tracker/blob/3c8f9fa79dd68b2e3f8206b7b51098b09736bf9d/snowplow-tracker/src/main/java/com/snowplowanalytics/core/utils/DeviceInfoMonitor.kt#L147) is a good way to fix it.

**Device informatoin (please complete the following information):**
 - Device: TANK 2 - Rugged Smartphone with Built-in Laser Projector
 - OS: Android 13
 - Version: SDK version - 6.0.3

**Comment by miike** [comment]
Thanks for the report @opengamer29 . Is there a corresponding bug report for the device by any chance as I'm wondering what value we should send (null, 0) instead or if it's possible to get the correct value somehow.

Wherever possible I want to avoid us implicitly hiding data issues as in some instances knowing that the battery level is incorrect and negative can be useful information to capture which would otherwise not necessarily be noticeable.

**Comment by opengamer29** [comment]
@miike I can't find any related bugs (it's a pretty rare device). I assume it may happen not only on this device but on some others that are not so good at following Android OS guidelines.

I think sending null is an appropriate compromise. We will be able to filter null values after enrichment and deal with it manually. The main issue is that due to scheme validation we can't use these data at all and we can't fix it by ourselves.

PS: I still can't get used to that somebody using our app on an Android device with a laser projector. It's hilarious :)

**Comment by mscwilson** [comment]
That is hilarious! I kinda want a rugged smartphone with built-in laser projector now.

I've created a PR for the patch, sending nulls as discussed. Might take a week or so to be released due to people on annual leave in the team.
