### ISSUE TITLE
Convert all Tracker.trackXXX functions into RxJava Observables

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-android-tracker#86]
This update will result in all processing of the android tracker being done in background threads reducing the load on the Main thread even more.

**Comment by duncan** [comment]
So, we're (6Wunderkinder) looking at going to Snowplow trackers across all our apps (Just did a bunch of work to port the iOS tracker to Mac OS and such) and just caught up on the changes to 0.3.0+. Overall, it's a big upgrade to what was there before, but.... How set are you on Rx? It’s 3,000 method into the DEX limit which is a lot for us.

**Comment by alexanderdean** [comment]
Hey @duncan! We had some very strong steer from the mobile team at Trello that Rx is the only robust way of doing async on Android... It certainly seems to stand up well to our testing.

We've looked around and haven't seen many other options - but if there were, we would be happy to have a `-rx` artifact and a `-otheroption` artifact.

What did you have in mind?

**Comment by alexanderdean** [comment]
As a note: an `-otheroption` would also be good for people on an incompatible version of Rx (if such a thing could exist)

**Comment by jbeemster** [comment]
Hey @duncan!  We could also look into if the RxAndroid version of Rx has a smaller DEX count than the RxJava library.

**Comment by duncan** [comment]
Fascinating. I'm ancillary to our Android team—technically, I’m Cross-Platform here at 6W—but I do concur that pulling out the AsyncTask stuff was good as not all events will come off the UIThread. And I’m personally spoiled by real futures and Scala and other mechanisms.. :) I’m actually intrigued—and also need to look at the hack that gets JDK 8 lambdas working...

Our folks here are arguing that for issuing GETs and POSTs against a collector, simply using an Executor with potentially a callback for the db row removal on success would probably do the trick and be a lot more minimal. I’m going to investigate up and down a bit tonight with the source code and see what more I can add...

**Comment by alexanderdean** [comment]
Sounds good @duncan - a minimal tracker that avoids AsyncTask's gotchas and Rx's size is certainly something we could add in. PR welcome!

**Comment by duncan** [comment]
Ok. I've got a PR started, but as I said there, it's definitely a work in progress, but I don't want to stay invisible on this to y'all as we work through it. On the other hand, I *don’t* expect y'all to pick it up with discussion of how it interacts with your Rx version of the tracker. 😏

https://github.com/snowplow/snowplow-android-tracker/pull/91

**Comment by alexanderdean** [comment]
Hey @duncan - many thanks, appreciate the early sharing and PR. Let's figure out how to support both approaches...
