### ISSUE TITLE
Add builder option to Tracker which allows custom logging modes to be set

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-android-tracker#94]

**Comment by jbeemster** [comment]
Should this be configured to allow the Tracker to have:

- No logging
- Info level
- Error level
- Debug level
- Verbose level

Or just an on/off switch for logging and not logging?

**Comment by alexanderdean** [comment]
I like the log level idea...

**Comment by jbeemster** [comment]
Me too!  Will need to go through everywhere that I am logging and make sure the levels make sense but would be a nice touch.

**Comment by jbeemster** [comment]
Putting a note here to flesh out logging throughout the application still.
